const supportData = {
  germany: {
    visa: "Visit the German Embassy website for visa application and requirements.",
    housing: "Use WG-Gesucht.de, Immowelt.de to find apartments.",
    job: "Check LinkedIn, Stepstone.de for job listings.",
    sim: "Top SIM providers: Vodafone, O2, Telekom.",
    banking: "Open online accounts via N26 or Deutsche Bank.",
  },
  france: {
    visa: "Apply via France-Visas official portal.",
    housing: "Check Leboncoin.fr and SeLoger.com.",
    job: "Use Pôle emploi and LinkedIn.",
    sim: "Orange, SFR, Bouygues Telecom are top providers.",
    banking: "BNP Paribas and Revolut are commonly used.",
  },
  netherlands: {
    visa: "Visit the Dutch Embassy website for visa application and requirements.",
    housing: "Use Pararius.com, Funda.nl to find apartments.",
    job: "Check Indeed.nl, LinkedIn for job listings.",
    sim: "KPN, Vodafone, T-Mobile are top providers.",
    banking: "Open accounts via ING or Rabobank.",
  },
  sweden: {
    visa: "Apply via the Swedish Migration Agency website.",
    housing: "Check Blocket.se and Hemnet.se for apartments.",
    job: "Use Arbetsförmedlingen and LinkedIn.",
    sim: "Telia, Tele2, Telenor are top providers.",
    banking: "Swedbank and SEB are commonly used.",
  },
  spain: {
    visa: "Visit the Spanish Embassy website for visa application and requirements.",
    housing: "Use Idealista.com, Fotocasa.es to find apartments.",
    job: "Check InfoJobs, LinkedIn for job listings.",
    sim: "Movistar, Orange, Vodafone are top providers.",
    banking: "Open accounts via Banco Santander or BBVA.",
  },
  italy: {
    visa: "Apply via the Italian Ministry of Foreign Affairs website.",
    housing: "Check Immobiliare.it and Casa.it for apartments.",
    job: "Use LinkedIn and InfoJobs for job listings.",
    sim: "TIM, Vodafone, WindTre are top providers.",
    banking: "Unicredit and Intesa Sanpaolo are commonly used.",
  },
  portugal: {
    visa: "Visit the Portuguese Embassy website for visa application and requirements.",
    housing: "Use Idealista.pt and OLX.pt to find apartments.",
    job: "Check LinkedIn and Sapo Emprego for job listings.",
    sim: "MEO, NOS, Vodafone are top providers.",
    banking: "Millennium BCP and Banco BPI are commonly used.",
  },
  austria: {
    visa: "Apply via the Austrian Embassy website for visa requirements.",
    housing: "Use Willhaben.at and ImmobilienScout24.at for apartments.",
    job: "Check Karriere.at and LinkedIn for job listings.",
    sim: "A1, Drei, and Magenta are top providers.",
    banking: "Erste Bank and Raiffeisen are commonly used.",
  },
  belgium: {
    visa: "Visit the Belgian Embassy website for visa application and requirements.",
    housing: "Check Immoweb.be and Zimmo.be for apartments.",
    job: "Use VDAB and LinkedIn for job listings.",
    sim: "Proximus, Orange, and Base are top providers.",
    banking: "KBC and BNP Paribas Fortis are commonly used.",
  },
  denmark: {
    visa: "Apply via the Danish Immigration Service website.",
    housing: "Check BoligPortal.dk and DBA.dk for apartments.",
    job: "Use Jobindex.dk and LinkedIn for job listings.",
    sim: "TDC, Telia, and 3 are top providers.",
    banking: "Danske Bank and Nordea are commonly used.",
  },
  finland: {
    visa: "Visit the Finnish Immigration Service website for visa application.",
    housing: "Check Oikotie.fi and Vuokraovi.com for apartments.",
    job: "Use TE Services and LinkedIn for job listings.",
