const languageSelect = document.getElementById('language-select');
const conversationArea = document.getElementById('conversation-area');
const modeToggle = document.getElementById('mode-toggle');

const vocabulary = {
  russian: [
    { ru: 'Что это?', bn: 'শতো এইতা?', bnMeaning: 'এটা কী?', en: 'What is this?' },
{ ru: 'Я хочу есть', bn: 'ইয়া খাচু ইইস্ত', bnMeaning: 'আমি খেতে চাই', en: 'I want to eat' },
{ ru: 'Где я?', bn: 'গ্দে ইয়া?', bnMeaning: 'আমি কোথায়?', en: 'Where am I?' },
{ ru: 'Как вас зовут?', bn: 'কাক ভাস জাভুত?', bnMeaning: 'আপনার নাম কী?', en: 'What’s your name?' },
{ ru: 'Мне плохо', bn: 'মনে প্লোখা', bnMeaning: 'আমার খারাপ লাগছে', en: 'I feel bad' },
{ ru: 'Я не знаю', bn: 'ইয়া নি zna-yu', bnMeaning: 'আমি জানি না', en: 'I don’t know' },
{ ru: 'Где гостиница?', bn: 'গ্দে গস্তিনিৎসা?', bnMeaning: 'হোটেল কোথায়?', en: 'Where is the hotel?' },
{ ru: 'Сколько вам лет?', bn: 'স্কলকো ভাম লিয়েত?', bnMeaning: 'আপনার বয়স কত?', en: 'How old are you?' },
{ ru: 'У меня болит голова', bn: 'উ মেনিয়া বলিত গালাভা', bnMeaning: 'আমার মাথা ব্যথা করছে', en: 'I have a headache' },
{ ru: 'Я из Бангладеш', bn: 'ইয়া ইজ বাংলাদেশ', bnMeaning: 'আমি বাংলাদেশ থেকে এসেছি', en: 'I am from Bangladesh' },
{ ru: 'Я люблю Россию', bn: 'ইয়া লিউব্লু রাসিয়ু', bnMeaning: 'আমি রাশিয়া ভালোবাসি', en: 'I love Russia' },
{ ru: 'Можно фотографировать?', bn: 'মোজনো ফোতোগ্রাফিরোভাত?', bnMeaning: 'আমি কি ছবি তুলতে পারি?', en: 'Can I take a photo?' },
{ ru: 'У вас есть Wi-Fi?', bn: 'উ ভাস ইইস্ত Wi-Fi?', bnMeaning: 'আপনার কি Wi-Fi আছে?', en: 'Do you have Wi-Fi?' },
{ ru: 'Счёт, пожалуйста', bn: 'শচёт, পাঝালুস্তা', bnMeaning: 'বিল দিন অনুগ্রহ করে', en: 'The bill, please' },
{ ru: 'Где метро?', bn: 'গ্দে মেত্রো?', bnMeaning: 'মেট্রো কোথায়?', en: 'Where is the metro?' },

{ ru: 'Привет', bn: 'প্রিভিয়েত', bnMeaning: 'হ্যালো', en: 'Hello' },
{ ru: 'Спасибо', bn: 'স্পাসিবো', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
{ ru: 'Как дела?', bn: 'কাক দেলা?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' },
{ ru: 'Здравствуйте', bn: 'জদরাভস্তভুইত্যে', bnMeaning: 'শুভ দিন', en: 'Hello (formal)' },
{ ru: 'Пожалуйста', bn: 'পাঝালুস্তা', bnMeaning: 'দয়া করে / স্বাগতম', en: "Please / You're welcome" },
{ ru: 'Извините', bn: 'ইজভিনিতিয়ে', bnMeaning: 'মাফ করবেন', en: 'Excuse me / Sorry' },
{ ru: 'Рад вас видеть', bn: 'রাত ভাস ভিদিত', bnMeaning: 'আপনাকে দেখে ভালো লাগলো', en: 'Nice to see you' },
{ ru: 'До свидания', bn: 'দা সভিদানিয়া', bnMeaning: 'বিদায়', en: 'Goodbye' },
{ ru: 'Добро пожаловать', bn: 'দাব্রো পাঝালাভাত', bnMeaning: 'স্বাগতম', en: 'Welcome' },
{ ru: 'Хорошо', bn: 'হারাশো', bnMeaning: 'ভালো', en: 'Good' },
{ ru: 'Плохо', bn: 'পলোখা', bnMeaning: 'খারাপ', en: 'Bad' },
{ ru: 'Где туалет?', bn: 'গ্দে তুয়ালেত?', bnMeaning: 'টয়লেট কোথায়?', en: 'Where is the toilet?' },
{ ru: 'Мне это нравится', bn: 'মনে এইতা ন্রাভিতসা', bnMeaning: 'আমার এটা পছন্দ', en: 'I like it' },
{ ru: 'Я не говорю по-русски', bn: 'ইয়া নি গাভারু পা রুস্কি', bnMeaning: 'আমি রাশিয়ান বলতে পারি না', en: "I don't speak Russian" },
{ ru: 'Повторите, пожалуйста', bn: 'পাফতারিতে পাঝালুস্তা', bnMeaning: 'অনুগ্রহ করে আবার বলুন', en: 'Please repeat' },
{ ru: 'Один билет, пожалуйста', bn: 'আদিন বিলিয়েত, পাঝালুস্তা', bnMeaning: 'একটি টিকিট দিন অনুগ্রহ করে', en: 'One ticket, please' },
{ ru: 'Где аптека?', bn: 'গ্দে আপত্যেকা?', bnMeaning: 'ফার্মেসি কোথায়?', en: 'Where is the pharmacy?' },
{ ru: 'Помогите мне!', bn: 'পামাগিতে ম্নে!', bnMeaning: 'আমাকে সাহায্য করুন!', en: 'Help me!' },
{ ru: 'Я потерялся', bn: 'ইয়া পাতেরিয়ালসা', bnMeaning: 'আমি পথ হারিয়েছি', en: 'I am lost' },
{ ru: 'Сколько это?', bn: 'স্কলকো এইতা?', bnMeaning: 'এটার দাম কত?', en: 'How much is this?' },
{ ru: 'Я устал', bn: 'ইয়া উস্তাল', bnMeaning: 'আমি ক্লান্ত', en: 'I am tired' },
{ ru: 'Я работаю здесь', bn: 'ইয়া রাবোতাইু জ্দেস', bnMeaning: 'আমি এখানে কাজ করি', en: 'I work here' },
{ ru: 'У меня есть работа', bn: 'উ মেনিয়া ইয়েস্ত রাবোতা', bnMeaning: 'আমার চাকরি আছে', en: 'I have a job' },
{ ru: 'Я ищу работу', bn: 'ইয়া ইশু রাবোতু', bnMeaning: 'আমি চাকরি খুঁজছি', en: 'I am looking for a job' },
{ ru: 'Где офис?', bn: 'গ্দে অফিস?', bnMeaning: 'অফিস কোথায়?', en: 'Where is the office?' },
{ ru: 'Когда начинается работа?', bn: 'কাগদা নাচিনায়েৎসা রাবোতা?', bnMeaning: 'কাজ কখন শুরু?', en: 'When does work start?' },
{ ru: 'У меня нет денег', bn: 'উ মেনিয়া নিৎ দেনেক', bnMeaning: 'আমার টাকা নেই', en: 'I have no money' },
{ ru: 'Сколько я получу?', bn: 'স্কলকো ইয়া পালুচু?', bnMeaning: 'আমি কত পাব?', en: 'How much will I get?' },
{ ru: 'Я живу в общежитии', bn: 'ইয়া জিভু ফ আফশিজিতিই', bnMeaning: 'আমি হোস্টেলে থাকি', en: 'I live in a hostel' },
{ ru: 'Где находится университет?', bn: 'গ্দে নাখোডিতসা ইউনিভার্সিতেত?', bnMeaning: 'বিশ্ববিদ্যালয় কোথায়?', en: 'Where is the university?' },
{ ru: 'Я студент медицинского факультета', bn: 'ইয়া স্টুডেন্ট মেদিত্সিনস্কাভা ফাকুল্তেতা', bnMeaning: 'আমি মেডিকেল ছাত্র', en: 'I am a medical student' },
{ ru: 'Когда у нас экзамен?', bn: 'কাগদা উ নাস একজামেন?', bnMeaning: 'আমাদের পরীক্ষা কখন?', en: 'When is our exam?' },
{ ru: 'У меня есть домашнее задание', bn: 'উ মেনিয়া ইয়েস্ত দামাশনিয়ে জাদানিয়ে', bnMeaning: 'আমার হোমওয়ার্ক আছে', en: 'I have homework' },
{ ru: 'Я изучаю русский язык', bn: 'ইয়া ইজুচায়ু রুস্কি ইয়াজিক', bnMeaning: 'আমি রাশিয়ান ভাষা শিখছি', en: 'I am learning Russian' },
{ ru: 'Можно войти?', bn: 'মোজনো ভাইটি?', bnMeaning: 'আমি কি ভিতরে আসতে পারি?', en: 'May I come in?' },
{ ru: 'У меня нет интернета', bn: 'উ মেনিয়া নিৎ ইন্টারনেতা', bnMeaning: 'আমার ইন্টারনেট নেই', en: 'I have no internet' },
{ ru: 'Это очень трудно', bn: 'এইতা ওচিন ত্রুদনা', bnMeaning: 'এটা খুব কঠিন', en: 'It is very difficult' },
{ ru: 'Повторите, пожалуйста, медленно', bn: 'পাফতারিতে, পাঝালুস্তা, মেদলেন্নো', bnMeaning: 'অনুগ্রহ করে ধীরে আবার বলুন', en: 'Please repeat slowly' },
{ ru: 'Я не понимаю задание', bn: 'ইয়া নি পনিমায়ু জাদানিয়ে', bnMeaning: 'আমি প্রশ্নটা বুঝতে পারছি না', en: 'I don’t understand the assignment' },
{ ru: 'Могу я задать вопрос?', bn: 'মাগু ইয়া জাদাত ভাপরোস?', bnMeaning: 'আমি কি প্রশ্ন করতে পারি?', en: 'Can I ask a question?' },
{ ru: 'Спасибо за помощь', bn: 'স্পাসিবো যা পোমোশ', bnMeaning: 'সাহায্যের জন্য ধন্যবাদ', en: 'Thank you for the help' },
{ ru: 'Мне нужна помощь', bn: 'মনে নুঝনা পোমোশ', bnMeaning: 'আমার সাহায্য দরকার', en: 'I need help' },
{ ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতে পা-আংলিস্কি?', bnMeaning: 'আপনি কি ইংরেজি বলেন?', en: 'Do you speak English?' },
{ ru: 'Где больница?', bn: 'গ্দে বালনিৎসা?', bnMeaning: 'হাসপাতাল কোথায়?', en: 'Where is the hospital?' },
{ ru: 'Мне нужно лекарство', bn: 'মনে নুঝনা লেকারস্তভো', bnMeaning: 'আমার ওষুধ দরকার', en: 'I need medicine' },
{ ru: 'Где ближайшая аптека?', bn: 'গ্দে ব্লিজাইশ্যায়া আপতেকা?', bnMeaning: 'নিকটতম ফার্মেসি কোথায়?', en: 'Where is the nearest pharmacy?' },
{ ru: 'Я потерял паспорт', bn: 'ইয়া পতেরিয়াল পাস্পর্ট', bnMeaning: 'আমি পাসপোর্ট হারিয়ে ফেলেছি', en: 'I lost my passport' },
{ ru: 'Позвоните в полицию', bn: 'পাজভানিতে ফ পলিতসিউ', bnMeaning: 'পুলিশে ফোন করুন', en: 'Call the police' },
{ ru: 'Где общественный транспорт?', bn: 'গ্দে আফশেস্তভেনি ট্রান্সপোর্ট?', bnMeaning: 'সার্বজনীন পরিবহন কোথায়?', en: 'Where is the public transport?' },
{ ru: 'Сколько стоит билет?', bn: 'স্কলকো স্তোইত বিলিয়েত?', bnMeaning: 'টিকিটের দাম কত?', en: 'How much is the ticket?' },
{ ru: 'Где ближайший банкомат?', bn: 'গ্দে ব্লিজাইশ্যি ব্যাংকোমাত?', bnMeaning: 'নিকটতম এটিএম কোথায়?', en: 'Where is the nearest ATM?' },
{ ru: 'Как снять деньги?', bn: 'কাক স্ন্যাৎ দেনগি?', bnMeaning: 'কিভাবে টাকা তুলবো?', en: 'How to withdraw money?' },
{ ru: 'Я иностранец', bn: 'ইয়া ইনাস্ত্রানিয়েত্স', bnMeaning: 'আমি বিদেশি', en: 'I am a foreigner' },
{ ru: 'Я здесь по учебе', bn: 'ইয়া জ্দেস পা উচোবে', bnMeaning: 'আমি পড়াশোনার জন্য এখানে', en: 'I am here for study' },
{ ru: 'Мне нужна виза', bn: 'মনে নুঝনা ভিজা', bnMeaning: 'আমার ভিসা দরকার', en: 'I need a visa' },
{ ru: 'У меня аллергия', bn: 'উ মেনিয়া অ্যালেরগিয়া', bnMeaning: 'আমার অ্যালার্জি আছে', en: 'I have an allergy' },
{ ru: 'Мне плохо', bn: 'মনে প্লোখা', bnMeaning: 'আমার খারাপ লাগছে', en: 'I feel sick' },
{ ru: 'Где я могу зарядить телефон?', bn: 'গ্দে ইয়া মাগু জরিয়াদিত তেলেফোন?', bnMeaning: 'আমি কোথায় ফোন চার্জ করতে পারি?', en: 'Where can I charge my phone?' },
{ ru: 'Как подключиться к Wi-Fi?', bn: 'কাক পদক্লুচিৎসা ক ওয়াইফাই?', bnMeaning: 'Wi-Fi-তে কিভাবে কানেক্ট করব?', en: 'How to connect to Wi-Fi?' },
{ ru: 'Моя квартира рядом', bn: 'মায়া কোয়ারতিরা রিয়াদম', bnMeaning: 'আমার অ্যাপার্টমেন্ট কাছেই', en: 'My apartment is nearby' },
{ ru: 'Сколько стоит аренда?', bn: 'স্কলকো স্তোইত অ্যারেনদা?', bnMeaning: 'ভাড়াটা কত?', en: 'How much is the rent?' },
{ ru: 'Я хочу купить это', bn: 'ইয়া খাচু কুপিত এটা', bnMeaning: 'আমি এটা কিনতে চাই', en: 'I want to buy this' },
{ ru: 'Сколько это стоит?', bn: 'স্কলকো এটা স্তোইত?', bnMeaning: 'এটার দাম কত?', en: 'How much does it cost?' },
{ ru: 'Можно дешевле?', bn: 'মোঝনা দিশেভ্লে?', bnMeaning: 'আরও সস্তা হবে?', en: 'Can it be cheaper?' },
{ ru: 'Где касса?', bn: 'গ্দে কাস্সা?', bnMeaning: 'ক্যাশ কাউন্টার কোথায়?', en: 'Where is the cashier?' },
{ ru: 'У вас есть сдача?', bn: 'উ ভাস ইয়েস্ত স্দাচা?', bnMeaning: 'আপনার কাছে খুচরা টাকা আছে?', en: 'Do you have change?' },
{ ru: 'Я плачу картой', bn: 'ইয়া প্লাছু কারতই', bnMeaning: 'আমি কার্ড দিয়ে দিচ্ছি', en: 'I’m paying by card' },
{ ru: 'Я плачу наличными', bn: 'ইয়া প্লাছু নালিচনিমি', bnMeaning: 'আমি নগদে দিচ্ছি', en: 'I’m paying in cash' },
{ ru: 'Мне нужна вода', bn: 'মনে নুঝনা ভাদা', bnMeaning: 'আমার পানি দরকার', en: 'I need water' },
{ ru: 'Я хочу поесть', bn: 'ইয়া খাচু পায়েস্ট', bnMeaning: 'আমি খেতে চাই', en: 'I want to eat' },
{ ru: 'Где ближайшее кафе?', bn: 'গ্দে ব্লিজাইশ্যায়া কাফে?', bnMeaning: 'নিকটতম ক্যাফে কোথায়?', en: 'Where is the nearest café?' },
{ ru: 'Принесите меню, пожалуйста', bn: 'প্রিনেসিতে মেন্যু, পাঝালুস্তা', bnMeaning: 'মেনু দিন, অনুগ্রহ করে', en: 'Please bring the menu' },
{ ru: 'Что вы порекомендуете?', bn: 'শতো ভি পারেকামেন্দুয়েতি?', bnMeaning: 'আপনি কী সুপারিশ করবেন?', en: 'What do you recommend?' },
{ ru: 'Я не ем мясо', bn: 'ইয়া নে ইম মিয়াসো', bnMeaning: 'আমি মাংস খাই না', en: 'I don’t eat meat' },
{ ru: 'Можно без лука?', bn: 'মোঝনা বেজ লুকা?', bnMeaning: 'পেঁয়াজ ছাড়া হবে?', en: 'Can it be without onion?' },
{ ru: 'Счёт, пожалуйста', bn: 'শ্চ্যত, পাঝালুস্তা', bnMeaning: 'বিল দিন, অনুগ্রহ করে', en: 'The bill, please' },
{ ru: 'Где остановка?', bn: 'গ্দে অস্তানভকা?', bnMeaning: 'স্টপেজ কোথায়?', en: 'Where is the stop?' },
{ ru: 'Этот автобус идёт в центр?', bn: 'এতত আফতোবুস ইদিয়ত ফ কেন্দ্র?', bnMeaning: 'এই বাস কি শহরে যায়?', en: 'Does this bus go to the center?' },
{ ru: 'Сколько стоит проезд?', bn: 'স্কলকো স্তোইত প্রায়েজদ?', bnMeaning: 'ভাড়া কত?', en: 'How much is the fare?' },
{ ru: 'У меня нет билета', bn: 'উ মেনিয়া নেট বিলিয়েতা', bnMeaning: 'আমার কাছে টিকিট নেই', en: 'I don’t have a ticket' },
{ ru: 'Когда следующий поезд?', bn: 'কগদা স্লেজুয়ুশ্চি পোয়েজদ?', bnMeaning: 'পরবর্তী ট্রেন কখন?', en: 'When is the next train?' },
{ ru: 'Я ищу квартиру', bn: 'ইয়া ইশু কভারতিরু', bnMeaning: 'আমি একটি ফ্ল্যাট খুঁজছি', en: 'I’m looking for an apartment' },
{ ru: 'Сколько стоит аренда?', bn: 'স্কলকো স্তোইত আরেন্দা?', bnMeaning: 'ভাড়া কত?', en: 'How much is the rent?' },
{ ru: 'Есть ли депозит?', bn: 'ইয়েস্ত লি দিপোজিত?', bnMeaning: 'ডিপোজিট লাগবে?', en: 'Is there a deposit?' },
{ ru: 'У меня есть документы', bn: 'উ মেনিয়া ইয়েস্ত দাকুমেনতি', bnMeaning: 'আমার কাগজপত্র আছে', en: 'I have the documents' },
{ ru: 'Где университет?', bn: 'গ্দে উনিভেরসিতেত?', bnMeaning: 'বিশ্ববিদ্যালয় কোথায়?', en: 'Where is the university?' },
{ ru: 'Я студент', bn: 'ইয়া স্তুদেন্ট', bnMeaning: 'আমি একজন ছাত্র', en: 'I am a student' },
{ ru: 'Мне нужно подать заявление', bn: 'মনে নুঝনা পাদাত জায়াভলেনিয়ে', bnMeaning: 'আমাকে আবেদন জমা দিতে হবে', en: 'I need to submit an application' },
{ ru: 'Где приёмная комиссия?', bn: 'গ্দে প্রিয়মনায়া কামিসসিয়া?', bnMeaning: 'ভর্তি অফিস কোথায়?', en: 'Where is the admissions office?' },
{ ru: 'Я хочу работать здесь', bn: 'ইয়া খাচু রাবোতাত জ্দেস', bnMeaning: 'আমি এখানে কাজ করতে চাই', en: 'I want to work here' },
{ ru: 'У меня встреча', bn: 'উ মেনিয়া স্তরেচা', bnMeaning: 'আমার একটি মিটিং আছে', en: 'I have a meeting' },
{ ru: 'Где больница?', bn: 'গ্দে বালনিৎসা?', bnMeaning: 'হাসপাতাল কোথায়?', en: 'Where is the hospital?' },
{ ru: 'Мне плохо', bn: 'মনে প্লাখা', bnMeaning: 'আমি অসুস্থ বোধ করছি', en: 'I feel sick' },
{ ru: 'Вызовите врача', bn: 'ভিজাভিতে ভ্রাচা', bnMeaning: 'ডাক্তার ডাকুন', en: 'Call the doctor' },
{ ru: 'У меня температура', bn: 'উ মেনিয়া তেম্পেরাতুরা', bnMeaning: 'আমার জ্বর হয়েছে', en: 'I have a fever' },
{ ru: 'Где аптека?', bn: 'গ্দে আপতেকা?', bnMeaning: 'ফার্মেসি কোথায়?', en: 'Where is the pharmacy?' },
{ ru: 'Мне нужны лекарства', bn: 'মনে নুঝনি লেকার্স্তভা', bnMeaning: 'আমার ওষুধ লাগবে', en: 'I need medicine' },
{ ru: 'Позовите полицию!', bn: 'পাজাভিতে পলিৎসিইউ!', bnMeaning: 'পুলিশ ডাকুন!', en: 'Call the police!' },
{ ru: 'Меня ограбили', bn: 'মেনিয়া আগরাবিলি', bnMeaning: 'আমাকে লুট করেছে', en: 'I was robbed' },
{ ru: 'Я потерял паспорт', bn: 'ইয়া পতেরিয়াল পাস্পর্ৎ', bnMeaning: 'আমার পাসপোর্ট হারিয়ে গেছে', en: 'I lost my passport' },
{ ru: 'Где находится посольство?', bn: 'গ্দে নাখোডিতসা পাসলস্তভা?', bnMeaning: 'দূতাবাস কোথায়?', en: 'Where is the embassy?' },
{ ru: 'Это мой друг', bn: 'এতা মই দ্রুক', bnMeaning: 'এটা আমার বন্ধু', en: 'This is my friend' },
{ ru: 'Как тебя зовут?', bn: 'কাক তিব্যা জাভুত?', bnMeaning: 'তোমার নাম কী?', en: 'What is your name?' },
{ ru: 'Рад тебя видеть', bn: 'রাত তিব্যা ভিডিচ', bnMeaning: 'তোমাকে দেখে ভালো লাগছে', en: 'Nice to see you' },
{ ru: 'Я скучаю по тебе', bn: 'ইয়া স্কুচায়ু পা তিব্যে', bnMeaning: 'আমি তোমাকে মিস করছি', en: 'I miss you' },
{ ru: 'Ты свободен сегодня?', bn: 'তি স্বাবোদেন সিভোদিন্যা?', bnMeaning: 'তুমি কি আজ ফ্রি?', en: 'Are you free today?' },
{ ru: 'Давай встретимся', bn: 'দাভাই স্ত্রেতিমসা', bnMeaning: 'চলো দেখা করি', en: 'Let’s meet' },
{ ru: 'Где ты живёшь?', bn: 'গ্দে তি ঝিভিওশ?', bnMeaning: 'তুমি কোথায় থাকো?', en: 'Where do you live?' },
{ ru: 'Это моя семья', bn: 'এতা মায়া সিমইয়া', bnMeaning: 'এটা আমার পরিবার', en: 'This is my family' },
{ ru: 'У тебя есть дети?', bn: 'উ তিব্যা ইয়েস্ত দেতি?', bnMeaning: 'তোমার কি সন্তান আছে?', en: 'Do you have children?' },
{ ru: 'Я женат / Я замужем', bn: 'ইয়া ঝেনাত / ইয়া জামুঝেম', bnMeaning: 'আমি বিবাহিত (পুরুষ / নারী)', en: 'I am married' },
{ ru: 'Ты женат?', bn: 'তি ঝেনাত?', bnMeaning: 'তুমি কি বিবাহিত?', en: 'Are you married?' },
{ ru: 'Я люблю тебя', bn: 'ইয়া লিউব্লু তিব্যা', bnMeaning: 'আমি তোমাকে ভালোবাসি', en: 'I love you' },
{ ru: 'Ты мне нравишься', bn: 'তি মনে ন্রাভিশ্স্যা', bnMeaning: 'তোমাকে আমার ভালো লাগে', en: 'I like you' },
{ ru: 'Давай поженимся', bn: 'দাভাই পাঝেনিমসিয়া', bnMeaning: 'চলো বিয়ে করি', en: 'Let’s get married' },
{ ru: 'Ты очень красивая', bn: 'তি ওচিন ক্রাসিভায়া', bnMeaning: 'তুমি অনেক সুন্দর (নারী)', en: 'You are very beautiful' },
{ ru: 'Ты очень красивый', bn: 'তি ওচিন ক্রাসিভি', bnMeaning: 'তুমি অনেক সুদর্শন (পুরুষ)', en: 'You are very handsome' },
{ ru: 'Можно твой номер?', bn: 'মোঝনা ত্ভোই নোমের?', bnMeaning: 'তোমার নাম্বার দিতে পারো?', en: 'Can I have your number?' },
{ ru: 'Напиши мне', bn: 'নাপিশি ম্নে', bnMeaning: 'আমাকে লিখো / মেসেজ করো', en: 'Text me' },
{ ru: 'Позвони мне', bn: 'পাজভানি ম্নে', bnMeaning: 'আমাকে ফোন করো', en: 'Call me' },
{ ru: 'До встречи!', bn: 'দা স্ত্রেচি!', bnMeaning: 'পরে দেখা হবে!', en: 'See you soon!' },
{ ru: 'Где аэропорт?', bn: 'গ্দে আয়ারাপোর্ত?', bnMeaning: 'বিমানবন্দর কোথায়?', en: 'Where is the airport?' },
{ ru: 'Когда вылет?', bn: 'কাগদা ভিলেত?', bnMeaning: 'ফ্লাইট কখন?', en: 'When is the flight?' },
{ ru: 'Мне нужно в аэропорт', bn: 'মনে নুঝনা ফ আয়ারাপোর্ত', bnMeaning: 'আমাকে বিমানবন্দরে যেতে হবে', en: 'I need to go to the airport' },
{ ru: 'У меня есть билет', bn: 'উ মেনিয়া ইয়েস্ত বিলিয়েত', bnMeaning: 'আমার টিকিট আছে', en: 'I have a ticket' },
{ ru: 'Где мой багаж?', bn: 'গ্দে মই বাগাঝ?', bnMeaning: 'আমার লাগেজ কোথায়?', en: 'Where is my luggage?' },
{ ru: 'Мне нужно такси в отель', bn: 'মনে নুঝনা তাকসি ফ আতেল', bnMeaning: 'আমার হোটেলে যাওয়ার জন্য ট্যাক্সি দরকার', en: 'I need a taxi to the hotel' },
{ ru: 'Забронируйте номер, пожалуйста', bn: 'জাব্রনিরুইতিয়ে নোমের, পাঝালুস্তা', bnMeaning: 'একটা রুম বুক করুন দয়া করে', en: 'Please book a room' },
{ ru: 'Сколько стоит номер?', bn: 'স্কলকো স্তোয়িত নোমের?', bnMeaning: 'রুমের দাম কত?', en: 'How much is the room?' },
{ ru: 'У вас есть свободные номера?', bn: 'উ ভাস ইয়েস্ত স্বাবোদনিয়ে নোমেরা?', bnMeaning: 'আপনারা কি ফাঁকা রুম আছে?', en: 'Do you have available rooms?' },
{ ru: 'Мне нужен одноместный номер', bn: 'মনে নুঝেন আদনামেস্তনি নোমের', bnMeaning: 'আমার একটা সিঙ্গেল রুম দরকার', en: 'I need a single room' },
{ ru: 'Сколько ночей вы будете?', bn: 'স্কলকো নচেই ভি বুদিতে?', bnMeaning: 'আপনি কয় রাত থাকবেন?', en: 'How many nights will you stay?' },
{ ru: 'Я останусь на три дня', bn: 'ইয়া অস্তানুস না ত্রি дня', bnMeaning: 'আমি তিন দিন থাকবো', en: 'I will stay for three days' },
{ ru: 'Можно паспорт, пожалуйста', bn: 'মোজনো পাশপোর্ত, পাঝালুস্তা', bnMeaning: 'পাসপোর্ট দিতে পারবেন দয়া করে?', en: 'May I have your passport, please?' },
{ ru: 'Где находится мой отель?', bn: 'গ্দে নাখোডিতসা মই আতেল?', bnMeaning: 'আমার হোটেল কোথায়?', en: 'Where is my hotel?' },
{ ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতিয়ে পা আঙ্গলিস্কি?', bnMeaning: 'আপনি কি ইংরেজি বলতে পারেন?', en: 'Do you speak English?' },
{ ru: 'Я не понимаю русский', bn: 'ইয়া নি পনিমায়ু রুসকি', bnMeaning: 'আমি রুশ ভাষা বুঝি না', en: 'I don’t understand Russian' },
{ ru: 'Где находится туристическое бюро?', bn: 'গ্দে নাখোডিতসা তুরিস্তিচেস্কায়া বিউরো?', bnMeaning: 'ট্যুরিস্ট অফিস কোথায়?', en: 'Where is the tourist office?' },
{ ru: 'Можно взять карту города?', bn: 'মোজনো ভজ্যাত কার্তু গোরাদা?', bnMeaning: 'শহরের মানচিত্র নিতে পারি?', en: 'Can I take a city map?' },
{ ru: 'Где находится вокзал?', bn: 'গ্দে নাখোডিতসা ভাকজাল?', bnMeaning: 'রেলস্টেশন কোথায়?', en: 'Where is the train station?' },
{ ru: 'Это далеко?', bn: 'এতা দালেকো?', bnMeaning: 'এটা কি দূরে?', en: 'Is it far?' },
{ ru: 'Сколько это стоит?', bn: 'স্কলকো এতা স্তোয়িত?', bnMeaning: 'এটার দাম কত?', en: 'How much does it cost?' },
{ ru: 'Это слишком дорого', bn: 'এতা স্লিশকম দোরগো', bnMeaning: 'এটা অনেক দামি', en: 'This is too expensive' },
{ ru: 'Можно подешевле?', bn: 'মোজনো পাদেশেভলে?', bnMeaning: 'আরও সস্তা হবে?', en: 'Can it be cheaper?' },
{ ru: 'Я покупаю это', bn: 'ইয়া পকুপায়ু এতা', bnMeaning: 'আমি এটা কিনছি', en: 'I am buying this' },
{ ru: 'Дайте, пожалуйста, чек', bn: 'দাইতে, পাঝালুস্তা, চেক', bnMeaning: 'দয়া করে রশিদ দিন', en: 'Please give me a receipt' },
{ ru: 'Где ближайший супермаркет?', bn: 'গ্দে ব্লিজাইশি সূপারমার্কেত?', bnMeaning: 'নিকটতম সুপারমার্কেট কোথায়?', en: 'Where is the nearest supermarket?' },
{ ru: 'У вас есть свежие овощи?', bn: 'উ ভাস ইয়েস্ত স্বেজিয়ে অভশি?', bnMeaning: 'আপনার কাছে তাজা সবজি আছে?', en: 'Do you have fresh vegetables?' },
{ ru: 'Я хочу купить фрукты', bn: 'ইয়া খাচু কুপিত ফ্রুকতি', bnMeaning: 'আমি ফল কিনতে চাই', en: 'I want to buy fruits' },
{ ru: 'У вас есть аптека рядом?', bn: 'উ ভাস ইয়েস্ত আপতেকা রিয়াদম?', bnMeaning: 'কাছাকাছি ফার্মেসি আছে?', en: 'Is there a pharmacy nearby?' },
{ ru: 'Мне нужно лекарство', bn: 'মনে নুঝনা লেকার্স্তভো', bnMeaning: 'আমার ওষুধ দরকার', en: 'I need medicine' },
{ ru: 'У меня болит голова', bn: 'উ মেনিয়া বলিত গোলোভা', bnMeaning: 'আমার মাথা ব্যথা করছে', en: 'I have a headache' },
{ ru: 'Позовите врача, пожалуйста', bn: 'পাজাভিতে ভ্রাচা, পাঝালুস্তা', bnMeaning: 'ডাক্তারকে ডাকুন দয়া করে', en: 'Please call a doctor' },
{ ru: 'Где ближайшая больница?', bn: 'গ্দে ব্লিজাইশায়া বলনিত্সা?', bnMeaning: 'নিকটতম হাসপাতাল কোথায়?', en: 'Where is the nearest hospital?' },
{ ru: 'У меня температура', bn: 'উ মেনিয়া তেমপেরাতুরা', bnMeaning: 'আমার জ্বর আছে', en: 'I have a fever' },
{ ru: 'Мне нужно в аптеку', bn: 'মনে নুঝনা ফ আপতেকু', bnMeaning: 'আমাকে ফার্মেসিতে যেতে হবে', en: 'I need to go to the pharmacy' },
{ ru: 'Где можно обменять деньги?', bn: 'গ্দে মোজনো আবমিন্যাত দেনগি?', bnMeaning: 'টাকা বিনিময় করা যাবে কোথায়?', en: 'Where can I exchange money?' },
{ ru: 'Я хочу обменять доллары на рубли', bn: 'ইয়া খাচু আবমিন্যাত দোলারি না রুবলি', bnMeaning: 'আমি ডলার রুবলে পরিবর্তন করতে চাই', en: 'I want to exchange dollars to rubles' },
{ ru: 'Где банкомат?', bn: 'গ্দে ব্যাংকমাত?', bnMeaning: 'এটিএম কোথায়?', en: 'Where is the ATM?' },
{ ru: 'Я потерял кошелек', bn: 'ইয়া পতেরিয়াল কাশেলিওক', bnMeaning: 'আমি আমার মানিব্যাগ হারিয়েছি', en: 'I lost my wallet' },
{ ru: 'Помогите, пожалуйста', bn: 'পামাগিতে, পাঝালুস্তা', bnMeaning: 'দয়া করে সাহায্য করুন', en: 'Please help me' },
{ ru: 'Я ищу квартиру', bn: 'ইয়া ইশু কভারতিরু', bnMeaning: 'আমি একটি ফ্ল্যাট খুঁজছি', en: 'I am looking for an apartment' },
{ ru: 'Сколько стоит аренда?', bn: 'স্কলকো স্তোয়িত আরেন্দা?', bnMeaning: 'ভাড়ার পরিমাণ কত?', en: 'How much is the rent?' },
{ ru: 'Квартира меблирована?', bn: 'কভারতিরা মেব্লিরোভান্না?', bnMeaning: 'ফ্ল্যাটটি কি আসবাবপত্রসহ?', en: 'Is the apartment furnished?' },
{ ru: 'Включены ли коммунальные услуги?', bn: 'ভক্লুচেনি লি কমুনালনি উস্লুগি?', bnMeaning: 'ইউটিলিটি বিল কি অন্তর্ভুক্ত?', en: 'Are utilities included?' },
{ ru: 'Можно посмотреть квартиру?', bn: 'মোজনো পাসমত্রেত কভারতিরু?', bnMeaning: 'ফ্ল্যাটটি কি দেখা যাবে?', en: 'Can I see the apartment?' },
{ ru: 'Сколько комнат?', bn: 'স্কলকো কোমনাত?', bnMeaning: 'কতটি রুম আছে?', en: 'How many rooms are there?' },
{ ru: 'Есть ли интернет?', bn: 'ইয়েস্ত লি ইন্টারনেত?', bnMeaning: 'ইন্টারনেট আছে কি?', en: 'Is there internet?' },
{ ru: 'Где ближайшая станция метро?', bn: 'গ্দে ব্লিজাইশায়া স্তান্সিয়া মেত্রো?', bnMeaning: 'নিকটতম মেট্রো স্টেশন কোথায়?', en: 'Where is the nearest metro station?' },
{ ru: 'Я хочу подписать контракт', bn: 'ইয়া খাচু পদপিসাত কনত্রাকত', bnMeaning: 'আমি চুক্তিতে সই করতে চাই', en: 'I want to sign the contract' },
{ ru: 'Когда можно заехать?', bn: 'কগদা মোজনো জায়েখাত?', bnMeaning: 'কখন উঠতে পারব?', en: 'When can I move in?' },
{ ru: 'Я съезжаю в следующем месяце', bn: 'ইয়া সিয়েজায়ু ফ স্লেদুইশ্যেম মিয়েসিয়েছিয়ে', bnMeaning: 'আমি পরের মাসে চলে যাব', en: 'I am moving out next month' },
{ ru: 'Мне нужно платить залог?', bn: 'মনে নুঝনা প্লাতিত জালোগ?', bnMeaning: 'আমাকে কি সিকিউরিটি ডিপোজিট দিতে হবে?', en: 'Do I need to pay a deposit?' },
{ ru: 'Кто мои соседи?', bn: 'কতো মই সাসেইদি?', bnMeaning: 'আমার প্রতিবেশী কারা?', en: 'Who are my neighbors?' },
{ ru: 'Это спокойный район?', bn: 'এতা স্পাকইনি রায়োন?', bnMeaning: 'এটি কি শান্ত এলাকা?', en: 'Is this a quiet area?' },
{ ru: 'У меня нет горячей воды', bn: 'উ মেনিয়া ন্যেত গরিয়াচেই ভাদুই', bnMeaning: 'আমার গরম পানি নেই', en: 'I have no hot water' },
{ ru: 'У вас есть отопление?', bn: 'উ ভাস ইয়েস্ত আতোপলেনিয়ে?', bnMeaning: 'গরমের ব্যবস্থা আছে?', en: 'Is there heating?' },
{ ru: 'У меня проблемы с электричеством', bn: 'উ মেনিয়া প্রাবলেমি স ইলেকত্রিচেস্তভাম', bnMeaning: 'আমার বিদ্যুৎ সমস্যায় পড়েছি', en: 'I have problems with electricity' },
{ ru: 'Я хочу поговорить с арендодателем', bn: 'ইয়া খাচু পাগাভারিত স আরেন্দাদাতেলিয়েম', bnMeaning: 'আমি বাড়িওয়ালার সাথে কথা বলতে চাই', en: 'I want to speak with the landlord' },
{ ru: 'Спасибо за помощь', bn: 'স্পাসিবো জা পামশচ', bnMeaning: 'সাহায্যের জন্য ধন্যবাদ', en: 'Thank you for the help' },
{ ru: 'Где платить за аренду?', bn: 'গ্দে প্লাতিত জা আরেন্দু?', bnMeaning: 'ভাড়া কোথায় দিতে হয়?', en: 'Where do I pay the rent?' },
{ ru: 'Где паспортный контроль?', bn: 'গ্দে পাস্পারতনি কন্ত্রোল?', bnMeaning: 'পাসপোর্ট কন্ট্রোল কোথায়?', en: 'Where is passport control?' },
{ ru: 'Вот мой паспорт', bn: 'ভত মই পাস্পারত', bnMeaning: 'এই নিন আমার পাসপোর্ট', en: 'Here is my passport' },
{ ru: 'У меня виза', bn: 'উ মেনিয়া ভিজা', bnMeaning: 'আমার ভিসা আছে', en: 'I have a visa' },
{ ru: 'Я турист', bn: 'ইয়া তুরিস্ট', bnMeaning: 'আমি একজন পর্যটক', en: 'I am a tourist' },
{ ru: 'Я студент', bn: 'ইয়া স্তুদিয়েন্ট', bnMeaning: 'আমি একজন ছাত্র', en: 'I am a student' },
{ ru: 'Вот мое приглашение', bn: 'ভত মায়ো প্রিগ্লাশেনিয়ে', bnMeaning: 'এই নিন আমার ইনভাইটেশন লেটার', en: 'Here is my invitation' },
{ ru: 'Сколько дней вы останетесь?', bn: 'স্কলকো দিনেই ভি আসতানিতেস?', bnMeaning: 'আপনি কয়দিন থাকবেন?', en: 'How many days will you stay?' },
{ ru: 'Где получить багаж?', bn: 'গ্দে পলুচিত বাগাজ?', bnMeaning: 'লাগেজ কোথা থেকে নিতে হয়?', en: 'Where do I collect baggage?' },
{ ru: 'Мой багаж потерян', bn: 'মই বাগাজ পাতেরিয়ান', bnMeaning: 'আমার লাগেজ হারিয়ে গেছে', en: 'My luggage is lost' },
{ ru: 'Это моя сумка', bn: 'এতা মায়া সুমকা', bnMeaning: 'এটা আমার ব্যাগ', en: 'This is my bag' },
{ ru: 'Где выход?', bn: 'গ্দে ভিতখাদ?', bnMeaning: 'বাহিরে যাওয়ার রাস্তা কোথায়?', en: 'Where is the exit?' },
{ ru: 'Мне нужна помощь', bn: 'মনে নুঝনা পামশচ', bnMeaning: 'আমার সাহায্য প্রয়োজন', en: 'I need help' },
{ ru: 'Я не говорю по-русски', bn: 'ইয়া নে গাভার্যু পারুস্কি', bnMeaning: 'আমি রুশ ভাষা জানি না', en: 'I don’t speak Russian' },
{ ru: 'Говорите по-английски?', bn: 'গাভারিতে পা-আংগ্লিস্কি?', bnMeaning: 'আপনি কি ইংরেজি বলতে পারেন?', en: 'Do you speak English?' },
{ ru: 'Где находится туалет?', bn: 'গ্দে নাখোডিতসা তুয়ালিয়েত?', bnMeaning: 'টয়লেট কোথায়?', en: 'Where is the toilet?' },
{ ru: 'У меня пересадка', bn: 'উ মেনিয়া পিরিসাদকা', bnMeaning: 'আমার ট্রানজিট আছে', en: 'I have a layover' },
{ ru: 'Где зал ожидания?', bn: 'গ্দে জল আঝিদানিয়া?', bnMeaning: 'ওয়েটিং এরিয়া কোথায়?', en: 'Where is the waiting area?' },
{ ru: 'У меня билет', bn: 'উ মেনিয়া বিলিয়েত', bnMeaning: 'আমার টিকিট আছে', en: 'I have a ticket' },
{ ru: 'Когда мой рейс?', bn: 'কগদা মই রেইস?', bnMeaning: 'আমার ফ্লাইট কখন?', en: 'When is my flight?' },
{ ru: 'Я опоздал на рейс', bn: 'ইয়া আপাজদাল না রেইস', bnMeaning: 'আমি ফ্লাইট মিস করেছি', en: 'I missed my flight' },
{ ru: 'У меня собеседование', bn: 'উ মেনিয়া সাবিয়েসেদাভানিয়ে', bnMeaning: 'আমার ইন্টারভিউ আছে', en: 'I have an interview' },
{ ru: 'Я ищу работу', bn: 'ইয়া ইশু রাবোতু', bnMeaning: 'আমি চাকরি খুঁজছি', en: 'I am looking for a job' },
{ ru: 'У меня есть опыт', bn: 'উ মেনিয়া ইয়েস্ট অপিত', bnMeaning: 'আমার অভিজ্ঞতা আছে', en: 'I have experience' },
{ ru: 'Вот мое резюме', bn: 'ভত মায়ো রিজুমে', bnMeaning: 'এই আমার রেজিউমে', en: 'Here is my resume' },
{ ru: 'Где офис?', bn: 'গ্দে অফিস?', bnMeaning: 'অফিস কোথায়?', en: 'Where is the office?' },
{ ru: 'Я работаю здесь', bn: 'ইয়া রাবোতাইু জ্দেস', bnMeaning: 'আমি এখানে কাজ করি', en: 'I work here' },
{ ru: 'Кто ваш начальник?', bn: 'ক্তো ভাশ নাচালনিক?', bnMeaning: 'আপনার বস কে?', en: 'Who is your boss?' },
{ ru: 'Я хочу работать', bn: 'ইয়া খাচু রাবোতাত', bnMeaning: 'আমি কাজ করতে চাই', en: 'I want to work' },
{ ru: 'Я свободен в выходные', bn: 'ইয়া সভাবোদিন ফ ভিতখাদনিয়ে', bnMeaning: 'আমি ছুটির দিনে ফ্রি থাকি', en: 'I am free on weekends' },
{ ru: 'Можете повторить?', bn: 'মোজিতি পাফতারিত?', bnMeaning: 'আপনি কি আবার বলতে পারেন?', en: 'Can you repeat that?' },
{ ru: 'Говорите медленно, пожалуйста', bn: 'গাভারিতে মিয়েদলেন্না, পাঝালুস্তা', bnMeaning: 'দয়া করে ধীরে বলুন', en: 'Please speak slowly' },
{ ru: 'Я не понимаю', bn: 'ইয়া নে পনিমায়ু', bnMeaning: 'আমি বুঝতে পারছি না', en: 'I don’t understand' },
{ ru: 'У меня диплом', bn: 'উ মেনিয়া দিপলোম', bnMeaning: 'আমার ডিপ্লোমা আছে', en: 'I have a diploma' },
{ ru: 'Какой график работы?', bn: 'কাকই গ্রাফিক রাবোতি?', bnMeaning: 'কাজের সময়সূচি কী?', en: 'What is the work schedule?' },
{ ru: 'Я работаю полный день', bn: 'ইয়া রাবোতাইু পলনি দেন', bnMeaning: 'আমি ফুল টাইম কাজ করি', en: 'I work full-time' },
{ ru: 'Есть ли у вас вакансии?', bn: 'ইয়েস্ট লি উ ভাস ভাকানসিই?', bnMeaning: 'আপনারা কি লোক নিচ্ছেন?', en: 'Do you have any vacancies?' },
{ ru: 'Когда я могу начать?', bn: 'কগদা ইয়া মাগু নাচাৎ?', bnMeaning: 'আমি কখন শুরু করতে পারি?', en: 'When can I start?' },
{ ru: 'Какая зарплата?', bn: 'কাকায়া জারপ্লাতা?', bnMeaning: 'বেতন কত?', en: 'What is the salary?' },
{ ru: 'Я согласен', bn: 'ইয়া সাগলাসেন', bnMeaning: 'আমি রাজি আছি', en: 'I agree' },
{ ru: 'Спасибо за возможность', bn: 'স্পাসিবো যা ভাজমজনাসচ', bnMeaning: 'সুযোগ দেওয়ার জন্য ধন্যবাদ', en: 'Thank you for the opportunity' },
{ ru: 'Я ищу квартиру', bn: 'ইয়া ইশু кварতিরু', bnMeaning: 'আমি একটি ফ্ল্যাট খুঁজছি', en: 'I am looking for an apartment' },
{ ru: 'Сколько стоит аренда?', bn: 'স্কল্কা স্তইৎ আরেনদা?', bnMeaning: 'ভাড়া কত?', en: 'How much is the rent?' },
{ ru: 'Где находится квартира?', bn: 'গ্দে নাখোদিতস্য квартира?', bnMeaning: 'ফ্ল্যাটটি কোথায়?', en: 'Where is the apartment located?' },
{ ru: 'Мне нужна комната', bn: 'মনে নুজনা কোমনাতা', bnMeaning: 'আমার একটি রুম দরকার', en: 'I need a room' },
{ ru: 'Можно посмотреть квартиру?', bn: 'মজনা পসমত্রеть кварти́ру?', bnMeaning: 'আমি কি ফ্ল্যাটটি দেখতে পারি?', en: 'Can I see the apartment?' },
{ ru: 'С кем я буду жить?', bn: 'স কেম ইয়া বুদু ঝিত?', bnMeaning: 'আমি কার সাথে থাকব?', en: 'With whom will I live?' },
{ ru: 'У меня есть сосед', bn: 'উ মেনিয়া ইয়েস্ট সাসিয়েদ', bnMeaning: 'আমার একজন প্রতিবেশী আছে', en: 'I have a neighbor' },
{ ru: 'Он хороший человек', bn: 'অন হারোশি চিলাভিয়েক', bnMeaning: 'সে একজন ভাল মানুষ', en: 'He is a good person' },
{ ru: 'Горячая вода есть?', bn: 'গরিয়াচায়া ভাদা ইয়েস্ট?', bnMeaning: 'গরম পানি আছে?', en: 'Is hot water available?' },
{ ru: 'Есть ли мебель?', bn: 'ইয়েস্ট লি মেবেল?', bnMeaning: 'ফার্নিচার আছে?', en: 'Is it furnished?' },
{ ru: 'Можно готовить дома?', bn: 'মজনা গাতোভিত দমা?', bnMeaning: 'বাসায় রান্না করা যাবে?', en: 'Can I cook at home?' },
{ ru: 'Сколько человек живет здесь?', bn: 'স্কল্কা চিলাভিয়েক ঝিভিয়ত জ্দেস?', bnMeaning: 'এখানে কয়জন থাকে?', en: 'How many people live here?' },
{ ru: 'У вас есть правила?', bn: 'উ ভাস ইয়েস্ট প্রাভিলা?', bnMeaning: 'আপনার কি কোনো নিয়ম আছে?', en: 'Do you have rules?' },
{ ru: 'Можно пригласить гостей?', bn: 'মজনা প্রিগলাসিত গাস্তেই?', bnMeaning: 'বন্ধু/অতিথি আনতে পারবো?', en: 'Can I invite guests?' },
{ ru: 'Когда платить аренду?', bn: 'কগদা প্লাতিত আরেনদু?', bnMeaning: 'ভাড়া কখন দিতে হবে?', en: 'When is the rent due?' },
{ ru: 'Включены ли коммунальные услуги?', bn: 'ভক্লুচনি লি কামুনালনি উস্লুগি?', bnMeaning: 'ইউটিলিটি চার্জ কি ভাড়ায় অন্তর্ভুক্ত?', en: 'Are utilities included?' },
{ ru: 'Где ближайший магазин?', bn: 'গ্দে ব্লিজাইশি magasins?', bnMeaning: 'কাছাকাছি দোকান কোথায়?', en: 'Where is the nearest shop?' },
{ ru: 'Я студент, мне нужно недорогое жилье', bn: 'ইয়া স্টুডেন্ট, মনে নুজনা নেদারাগোই জেলিয়ো', bnMeaning: 'আমি ছাত্র, আমার সস্তা বাসা দরকার', en: 'I am a student, I need cheap accommodation' },
{ ru: 'Могу я остаться на месяц?', bn: 'মাগু ইয়া অস্তাচся না মেসিয়াতস?', bnMeaning: 'আমি কি এক মাস থাকতে পারি?', en: 'Can I stay for a month?' },
{ ru: 'Спасибо за информацию', bn: 'স্পাসিবো যা ইনফারমাতসিয়ু', bnMeaning: 'তথ্য দেওয়ার জন্য ধন্যবাদ', en: 'Thank you for the information' },
{ ru: 'Где находится аэропорт?', bn: 'গ্দে নাখোদিতস্য আয়েরোপোर्त?', bnMeaning: 'বিমানবন্দর কোথায়?', en: 'Where is the airport?' },
{ ru: 'Мне нужен билет', bn: 'মনে নুঝেন বিলিয়েত', bnMeaning: 'আমার একটি টিকিট দরকার', en: 'I need a ticket' },
{ ru: 'Где паспортный контроль?', bn: 'গ্দে পাশপর্তনি কান্ত্রোল?', bnMeaning: 'পাসপোর্ট চেক কোথায়?', en: 'Where is passport control?' },
{ ru: 'Я путешествую по учёбе', bn: 'ইয়া পুতেশেস্টভুইু পা উচোবি', bnMeaning: 'আমি পড়াশোনার জন্য ভ্রমণ করছি', en: 'I am traveling for study' },
{ ru: 'Где мой багаж?', bn: 'গ্দে ময় বাগাশ?', bnMeaning: 'আমার ব্যাগ কোথায়?', en: 'Where is my luggage?' },
{ ru: 'Мой рейс задерживается', bn: 'মই রেইস জাদেরঝিভাইতস্য', bnMeaning: 'আমার ফ্লাইট দেরি করছে', en: 'My flight is delayed' },
{ ru: 'Где находится отель?', bn: 'গ্দে নাখোদিতস্য আতের?', bnMeaning: 'হোটেল কোথায়?', en: 'Where is the hotel?' },
{ ru: 'У меня бронь на имя...', bn: 'উ মেনিয়া ব্রোণ না ইম্যা...', bnMeaning: 'আমার বুকিং হয়েছে নাম...', en: 'I have a reservation under the name...' },
{ ru: 'Сколько стоит ночь?', bn: 'স্কল্কা স্তইত নোচ?', bnMeaning: 'এক রাতের খরচ কত?', en: 'How much is one night?' },
{ ru: 'Есть ли завтрак?', bn: 'ইয়েস্ট লি জাভত্রাক?', bnMeaning: 'নাস্তা অন্তর্ভুক্ত?', en: 'Is breakfast included?' },
{ ru: 'Где находится посольство?', bn: 'গ্দে নাখোদিতস্য পাসলস্তভা?', bnMeaning: 'দূতাবাস কোথায়?', en: 'Where is the embassy?' },
{ ru: 'Мне нужна виза', bn: 'মনে নুজনা ভিজা', bnMeaning: 'আমার ভিসা দরকার', en: 'I need a visa' },
{ ru: 'Сколько дней можно остаться?', bn: 'স্কল্কা দনেই মজনা অস্তাচся?', bnMeaning: 'কয়দিন থাকা যাবে?', en: 'How many days can I stay?' },
{ ru: 'Вот мой паспорт', bn: 'ভোত ময় পাশপোর্ট', bnMeaning: 'এই নিন আমার পাসপোর্ট', en: 'Here is my passport' },
{ ru: 'У вас есть карта города?', bn: 'উ ভাস ইয়েস্ট কার্তা গোরদা?', bnMeaning: 'আপনার কাছে শহরের মানচিত্র আছে?', en: 'Do you have a city map?' },
{ ru: 'Где я могу обменять деньги?', bn: 'গ্দে ইয়া মাগু ওবমেনিয়াত দেনগি?', bnMeaning: 'আমি কোথায় টাকা এক্সচেঞ্জ করতে পারি?', en: 'Where can I exchange money?' },
{ ru: 'Мне нужна помощь', bn: 'মনে নুজনা পমোশ', bnMeaning: 'আমার সাহায্য দরকার', en: 'I need help' },
{ ru: 'Как я могу добраться до города?', bn: 'কাক ইয়া মাগু দাব্রাতসা দা গোরাদা?', bnMeaning: 'আমি কীভাবে শহরে যেতে পারি?', en: 'How can I get to the city?' },
{ ru: 'Есть ли трансфер?', bn: 'ইয়েস্ট লি ত্রান্সফেয়ার?', bnMeaning: 'ট্রান্সফার সার্ভিস আছে?', en: 'Is there a transfer service?' },
{ ru: 'Спасибо за помощь', bn: 'স্পাসিবো যা পমোশ', bnMeaning: 'সাহায্যের জন্য ধন্যবাদ', en: 'Thank you for the help' },
{ ru: 'Мне плохо', bn: 'মনে প্লোখা', bnMeaning: 'আমি অসুস্থ', en: 'I feel sick' },
{ ru: 'У меня болит голова', bn: 'উ মেনিয়া বালিত গালাভা', bnMeaning: 'আমার মাথা ব্যথা করছে', en: 'I have a headache' },
{ ru: 'У меня температура', bn: 'উ মেনিয়া তেমপেরাতুরা', bnMeaning: 'আমার জ্বর আছে', en: 'I have a fever' },
{ ru: 'Мне нужен врач', bn: 'মনে নুঝেন ভ্রাচ', bnMeaning: 'আমার ডাক্তার দরকার', en: 'I need a doctor' },
{ ru: 'Где больница?', bn: 'গ্দে বালনিত্সা?', bnMeaning: 'হাসপাতাল কোথায়?', en: 'Where is the hospital?' },
{ ru: 'У меня аллергия', bn: 'উ মেনিয়া আলেরগিয়া', bnMeaning: 'আমার অ্যালার্জি আছে', en: 'I have an allergy' },
{ ru: 'Это срочно', bn: 'এতা স্রোচনা', bnMeaning: 'এটা জরুরি', en: 'It’s urgent' },
{ ru: 'У меня болит живот', bn: 'উ মেনিয়া বালিত জিভোত', bnMeaning: 'আমার পেট ব্যথা করছে', en: 'I have a stomach ache' },
{ ru: 'Мне нужна скорая помощь', bn: 'মনে নুজনা স্কোরায়া পমোশ', bnMeaning: 'আমার অ্যাম্বুলেন্স দরকার', en: 'I need an ambulance' },
{ ru: 'Вы можете мне помочь?', bn: 'ভি মোঝিতে মনে পামোচ?', bnMeaning: 'আপনি কি আমাকে সাহায্য করতে পারেন?', en: 'Can you help me?' },
{ ru: 'Мне нужно лекарство', bn: 'মনে নুঝনা লেকারস্তভা', bnMeaning: 'আমার ওষুধ দরকার', en: 'I need medicine' },
{ ru: 'Где ближайшая аптека?', bn: 'গ্দে ব্লিজাইশায়া আপত্যেকা?', bnMeaning: 'নিকটতম ফার্মেসি কোথায়?', en: 'Where is the nearest pharmacy?' },
{ ru: 'Я упал и ударился', bn: 'ইয়া উপাল ই উদারিলস্য', bnMeaning: 'আমি পড়ে গেছি এবং আঘাত পেয়েছি', en: 'I fell and got hurt' },
{ ru: 'Мне нужно сделать анализ крови', bn: 'মনে নুঝনা স্দেলাত আনালিজ ক্রোভি', bnMeaning: 'আমার রক্ত পরীক্ষা দরকার', en: 'I need a blood test' },
{ ru: 'У меня диабет', bn: 'উ মেনিয়া ডিয়াবিয়েত', bnMeaning: 'আমার ডায়াবেটিস আছে', en: 'I have diabetes' },
{ ru: 'Это инфекция?', bn: 'এতা ইনফেকসিয়া?', bnMeaning: 'এটা কি ইনফেকশন?', en: 'Is it an infection?' },
{ ru: 'Когда будет лучше?', bn: 'কগদা বুদিত লুচশে?', bnMeaning: 'কখন ভালো বোধ করবো?', en: 'When will I feel better?' },
{ ru: 'Мне нужна операция', bn: 'মনে নুঝনা অপরাতসিয়া', bnMeaning: 'আমার অপারেশন দরকার', en: 'I need an operation' },
{ ru: 'У меня нет страховки', bn: 'উ মেনিয়া নেত স্ত্রাখোভকি', bnMeaning: 'আমার স্বাস্থ্যবীমা নেই', en: 'I don’t have insurance' },
{ ru: 'Спасибо, доктор', bn: 'স্পাসিবো, দক্তর', bnMeaning: 'ধন্যবাদ, ডাক্তার', en: 'Thank you, doctor' },
{ ru: 'Сколько это стоит?', bn: 'স্কোলকা এতা স্তইইত?', bnMeaning: 'এটার দাম কত?', en: 'How much does it cost?' },
{ ru: 'Это слишком дорого', bn: 'এতা স্লিশকম দোরগো', bnMeaning: 'এটা অনেক দামী', en: 'It’s too expensive' },
{ ru: 'У вас есть подешевле?', bn: 'উ ভাস ইস্ত পাদিশেভলে?', bnMeaning: 'আপনার কি সস্তা কিছু আছে?', en: 'Do you have something cheaper?' },
{ ru: 'Я хочу купить это', bn: 'ইয়া খাচু কুপিত এতা', bnMeaning: 'আমি এটা কিনতে চাই', en: 'I want to buy this' },
{ ru: 'Можно заплатить картой?', bn: 'মোঝনা জাপ্লাতিত কার্তই?', bnMeaning: 'আমি কি কার্ডে পেমেন্ট করতে পারি?', en: 'Can I pay by card?' },
{ ru: 'Я плачу наличными', bn: 'ইয়া প্লাচু নালিচনিমি', bnMeaning: 'আমি নগদে দিচ্ছি', en: 'I’m paying in cash' },
{ ru: 'У вас есть сдача?', bn: 'উ ভাস ইস্ত স্দাচা?', bnMeaning: 'আপনার কাছে কি খুচরা আছে?', en: 'Do you have change?' },
{ ru: 'Где примерочная?', bn: 'গ্দে প্রিমেরোচনায়া?', bnMeaning: 'পরীক্ষা করার রুম কোথায়?', en: 'Where is the fitting room?' },
{ ru: 'Можно примерить?', bn: 'মোঝনা প্রিমেরিত?', bnMeaning: 'আমি কি এটা পরতে পারি?', en: 'Can I try this on?' },
{ ru: 'Мне это нравится', bn: 'মনে এতা ন্রাভিতসা', bnMeaning: 'এটা আমার ভালো লেগেছে', en: 'I like it' },
{ ru: 'У вас есть другой размер?', bn: 'উ ভাস ইস্ত দ্রোগই রজমের?', bnMeaning: 'আপনার কি অন্য সাইজ আছে?', en: 'Do you have another size?' },
{ ru: 'Я просто смотрю', bn: 'ইয়া প্রস্ত স্মাত্রু', bnMeaning: 'আমি শুধু দেখছি', en: 'I’m just looking' },
{ ru: 'Это подарок', bn: 'এতা পাদারাক', bnMeaning: 'এটা একটি উপহার', en: 'It’s a gift' },
{ ru: 'Где касса?', bn: 'গ্দে কাসসা?', bnMeaning: 'ক্যাশ কাউন্টার কোথায়?', en: 'Where is the checkout?' },
{ ru: 'Вы открыты?', bn: 'ভি আক্রিতি?', bnMeaning: 'আপনারা কি খোলা?', en: 'Are you open?' },
{ ru: 'У вас есть продукты?', bn: 'উ ভাস ইস্ত প্রাদুকতি?', bnMeaning: 'আপনারা কি খাবার বিক্রি করেন?', en: 'Do you sell groceries?' },
{ ru: 'Я ищу сувенир', bn: 'ইয়া ইশু সুভেনির', bnMeaning: 'আমি একটা সুভেনির খুঁজছি', en: 'I’m looking for a souvenir' },
{ ru: 'Это натуральное?', bn: 'এতা নাতুরালনয়ে?', bnMeaning: 'এটা কি প্রাকৃতিক?', en: 'Is it natural?' },
{ ru: 'Можно это вернуть?', bn: 'মোঝনা এতা ভারনুৎ?', bnMeaning: 'এটা কি ফেরত দেওয়া যাবে?', en: 'Can I return this?' },
{ ru: 'У вас есть скидка?', bn: 'উ ভাস ইস্ত স্কিদকা?', bnMeaning: 'আপনারা কি ছাড় দিচ্ছেন?', en: 'Do you have a discount?' },
{ ru: 'Где находится аэропорт?', bn: 'গ্দে নাখোদিতসা আয়ারাপোर्त?', bnMeaning: 'বিমানবন্দর কোথায়?', en: 'Where is the airport?' },
{ ru: 'Как доехать до центра?', bn: 'কাক দায়েখাত দো কেন্দ্র?', bnMeaning: 'শহরের কেন্দ্রে কীভাবে যাব?', en: 'How do I get to the city center?' },
{ ru: 'Мне нужно такси', bn: 'মনে নুঝনা টাকসি', bnMeaning: 'আমার ট্যাক্সি দরকার', en: 'I need a taxi' },
{ ru: 'Сколько стоит доехать?', bn: 'স্কোলকা স্তইইত দায়েখাত?', bnMeaning: 'যাওয়ার খরচ কত?', en: 'How much is the fare?' },
{ ru: 'Остановите здесь, пожалуйста', bn: 'আস্তানাভিতে জ্দেস পাঝালুস্তা', bnMeaning: 'দয়া করে এখানে থামান', en: 'Please stop here' },
{ ru: 'У меня забронирован номер', bn: 'উ মেন্যা জাব্রানিরাভান নোমের', bnMeaning: 'আমার রুম রিজার্ভ করা আছে', en: 'I have a reservation' },
{ ru: 'Есть свободные номера?', bn: 'ইস্ত স্ভাবদনি নোমেরা?', bnMeaning: 'খালি রুম আছে?', en: 'Do you have available rooms?' },
{ ru: 'На сколько ночей?', bn: 'না স্কোলকা নচেই?', bnMeaning: 'কত রাতের জন্য?', en: 'For how many nights?' },
{ ru: 'Сколько стоит одна ночь?', bn: 'স্কোলকা স্তইইত আদনা নোচ?', bnMeaning: 'এক রাতের দাম কত?', en: 'How much for one night?' },
{ ru: 'Где здесь туалет?', bn: 'গ্দে জ্দেস তুয়ালেত?', bnMeaning: 'টয়লেট কোথায়?', en: 'Where is the toilet?' },
{ ru: 'Можно мне карту города?', bn: 'মোঝনা মেনে কার্তু গোরাদা?', bnMeaning: 'আমি কি শহরের মানচিত্র পেতে পারি?', en: 'Can I have a city map?' },
{ ru: 'Когда выезжать?', bn: 'কাগদা ভিয়েজ্জাত?', bnMeaning: 'কখন চেকআউট করতে হবে?', en: 'When is check-out?' },
{ ru: 'Какой адрес отеля?', bn: 'কাকই আদ্রেস আতেল্যা?', bnMeaning: 'হোটেলের ঠিকানা কী?', en: 'What’s the hotel address?' },
{ ru: 'Где автобусная остановка?', bn: 'গ্দে আফ্তবুসনায়া আস্তানোভকা?', bnMeaning: 'বাসস্ট্যান্ড কোথায়?', en: 'Where is the bus stop?' },
{ ru: 'Можно забронировать онлайн?', bn: 'মোঝনা জাব্রানিরাভাত অনলাইন?', bnMeaning: 'আমি কি অনলাইনে বুক করতে পারি?', en: 'Can I book online?' },
{ ru: 'У меня есть багаж', bn: 'উ মেন্যা ইস্ত বাগাজ', bnMeaning: 'আমার ব্যাগেজ আছে', en: 'I have luggage' },
{ ru: 'Где мой багаж?', bn: 'গ্দে মই বাগাজ?', bnMeaning: 'আমার ব্যাগ কোথায়?', en: 'Where is my luggage?' },
{ ru: 'Мне нужен переводчик', bn: 'মনে নুঝন পেরেভদচিক', bnMeaning: 'আমার একজন দোভাষী দরকার', en: 'I need a translator' },
{ ru: 'Это мой паспорт', bn: 'এতা মই পাসপোর্ত', bnMeaning: 'এটা আমার পাসপোর্ট', en: 'This is my passport' },
{ ru: 'Где можно обменять деньги?', bn: 'গ্দে মোঝনা আবমেন্যাত দেনগি?', bnMeaning: 'কোথায় টাকা বিনিময় করা যায়?', en: 'Where can I exchange money?' },
{ ru: 'Мне плохо', bn: 'মনে প্লোখা', bnMeaning: 'আমার শরীর খারাপ লাগছে', en: 'I feel unwell' },
{ ru: 'У меня болит голова', bn: 'উ মেন্যা বালিত গোলোভা', bnMeaning: 'আমার মাথা ব্যথা করছে', en: 'I have a headache' },
{ ru: 'У меня температура', bn: 'উ মেন্যা তেমপেরাতুরা', bnMeaning: 'আমার জ্বর', en: 'I have a fever' },
{ ru: 'Где ближайшая больница?', bn: 'গ্দে ব্লিজাইশায়া বালনিত্সা?', bnMeaning: 'সবচেয়ে কাছের হাসপাতাল কোথায়?', en: 'Where is the nearest hospital?' },
{ ru: 'Мне нужен врач', bn: 'মনে নুঝেন ভ্রাচ', bnMeaning: 'আমার একজন ডাক্তার দরকার', en: 'I need a doctor' },
{ ru: 'У меня аллергия', bn: 'উ মেন্যা আলের্গিয়া', bnMeaning: 'আমার অ্যালার্জি আছে', en: 'I have an allergy' },
{ ru: 'Это срочно', bn: 'এতা স্রোচনা', bnMeaning: 'এটা জরুরি', en: 'It’s urgent' },
{ ru: 'Где аптека?', bn: 'গ্দে আপ্তека?', bnMeaning: 'ফার্মেসি কোথায়?', en: 'Where is the pharmacy?' },
{ ru: 'Мне нужно лекарство', bn: 'মনে নুঝনা লেকার্সত্বা', bnMeaning: 'আমার ওষুধ দরকার', en: 'I need medicine' },
{ ru: 'У меня болит живот', bn: 'উ মেন্যা বালিত জিভত', bnMeaning: 'আমার পেট ব্যথা করছে', en: 'I have stomach pain' },
{ ru: 'У вас есть антибиотик?', bn: 'উ ভাস ইস্ত আনতিবিওতিক?', bnMeaning: 'আপনার কাছে অ্যান্টিবায়োটিক আছে?', en: 'Do you have antibiotics?' },
{ ru: 'Сколько стоит приём?', bn: 'স্কোলকা স্তইইত প্রিয়ম?', bnMeaning: 'ডাক্তারের পরামর্শের ফি কত?', en: 'How much is the consultation?' },
{ ru: 'Когда я могу прийти?', bn: 'কাগদা ইয়া মাগু প্রিইতি?', bnMeaning: 'আমি কখন আসতে পারি?', en: 'When can I come?' },
{ ru: 'У меня коронавирус', bn: 'উ মেন্যা কারানাভিরুস', bnMeaning: 'আমার করোনা হয়েছে', en: 'I have coronavirus' },
{ ru: 'Нужна скорая помощь', bn: 'নুঝনা স্কোরায়া পোমোশ্চ', bnMeaning: 'অ্যাম্বুলেন্স দরকার', en: 'Need emergency help (ambulance)' },
{ ru: 'Я чувствую слабость', bn: 'ইয়া চুস্তভুই স্লাবাস্‌ৎ', bnMeaning: 'আমি দুর্বল অনুভব করছি', en: 'I feel weak' },
{ ru: 'Можно мне рецепт?', bn: 'মোঝনা মেনে রেৎসেপ্‌ত?', bnMeaning: 'আমি কি প্রেসক্রিপশন পেতে পারি?', en: 'Can I have a prescription?' },
{ ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতে পা আংগ্লিস্কি?', bnMeaning: 'আপনি কি ইংরেজি বলেন?', en: 'Do you speak English?' },
{ ru: 'Я боюсь уколов', bn: 'ইয়া বায়ুস উকালাফ', bnMeaning: 'আমি ইনজেকশনে ভয় পাই', en: 'I’m afraid of injections' },
{ ru: 'Сделайте, пожалуйста, не больно', bn: 'জ্দেলাইতে পাঝালুস্তা নে বালনা', bnMeaning: 'দয়া করে ব্যথা না দেন', en: 'Please don’t hurt' },
{ ru: 'Я ищу работу', bn: 'ইয়া ইশু রাবোতু', bnMeaning: 'আমি চাকরি খুঁজছি', en: 'I am looking for a job' },
{ ru: 'У меня есть опыт работы', bn: 'উ মেন্যা ইস্ত ওপিত রাবোতি', bnMeaning: 'আমার কাজের অভিজ্ঞতা আছে', en: 'I have work experience' },
{ ru: 'Где находится офис?', bn: 'গ্দে নাখোদিত্সা অফিস?', bnMeaning: 'অফিস কোথায়?', en: 'Where is the office?' },
{ ru: 'Когда собеседование?', bn: 'কগ্দা সাবেসেদাভানিয়ে?', bnMeaning: 'ইন্টারভিউ কখন?', en: 'When is the interview?' },
{ ru: 'Что мне нужно принести?', bn: 'শ্তো মেনে নুঝনা প্রিনেসতি?', bnMeaning: 'আমাকে কী আনতে হবে?', en: 'What should I bring?' },
{ ru: 'Это моя визитная карточка', bn: 'এতা মায়া ভিজিতনায়া কার্তচকা', bnMeaning: 'এটা আমার ভিজিটিং কার্ড', en: 'This is my business card' },
{ ru: 'Я работаю в офисе', bn: 'ইয়া রাবোতাইু ভ অফিসে', bnMeaning: 'আমি অফিসে কাজ করি', en: 'I work in an office' },
{ ru: 'Мне нужно отправить e-mail', bn: 'মনে নুঝনা আতপ্রাভিত ই-মেইল', bnMeaning: 'আমাকে ইমেইল পাঠাতে হবে', en: 'I need to send an email' },
{ ru: 'Мой начальник хороший', bn: 'ময় নাচালনিক খারোশি', bnMeaning: 'আমার বস ভালো', en: 'My boss is good' },
{ ru: 'Я занят на работе', bn: 'ইয়া জান্যাত না রাবোতে', bnMeaning: 'আমি কাজ নিয়ে ব্যস্ত', en: 'I am busy at work' },
{ ru: 'У нас встреча в 10 утра', bn: 'উ নাস স্ত্রেচা ফ দশ উত্রা', bnMeaning: 'আমাদের সকাল ১০টায় মিটিং', en: 'We have a meeting at 10am' },
{ ru: 'Я не понимаю задание', bn: 'ইয়া নে পানিমায়ু জাদানিয়ে', bnMeaning: 'আমি কাজটা বুঝতে পারছি না', en: 'I don’t understand the task' },
{ ru: 'Сколько платят?', bn: 'স্কোলকা প্লাতিয়াত?', bnMeaning: 'বেতন কত?', en: 'How much do they pay?' },
{ ru: 'Мне нужен перерыв', bn: 'মনে নুঝেন পেরিরিভ', bnMeaning: 'আমার একটু বিরতি দরকার', en: 'I need a break' },
{ ru: 'Где мой стол?', bn: 'গ্দে ময় স্তল?', bnMeaning: 'আমার ডেস্ক কোথায়?', en: 'Where is my desk?' },
{ ru: 'Можно использовать интернет?', bn: 'মোঝনা ইস্পল্জাভাত ইন্টারনেত?', bnMeaning: 'ইন্টারনেট ব্যবহার করা যাবে?', en: 'Can I use the internet?' },
{ ru: 'Работа закончена', bn: 'রাবোতা জাকনচেনা', bnMeaning: 'কাজ শেষ', en: 'Work is finished' },
{ ru: 'Мне нужна помощь с отчётом', bn: 'মনে নুঝনা পোমোশ্চ স অচোতম', bnMeaning: 'আমাকে রিপোর্টে সাহায্য দরকার', en: 'I need help with the report' },
{ ru: 'Я устал от работы', bn: 'ইয়া উস্তাল অত রাবোতে', bnMeaning: 'আমি কাজ করে ক্লান্ত', en: 'I am tired from work' },
{ ru: 'Спасибо за сотрудничество', bn: 'স্পাসিবো за সত্রুদনিচেস্তভো', bnMeaning: 'সহযোগিতার জন্য ধন্যবাদ', en: 'Thank you for the cooperation' },
{ ru: 'Сколько времени занимает дорога до университета?', bn: 'স্কলকো ভরেমেনি জানিমায়েত দরোগা দো উনিভার্সিতেতা?', bnMeaning: 'বিশ্ববিদ্যালয়ে যেতে কত সময় লাগে?', en: 'How long does it take to get to the university?' },
{ ru: 'Я ищу работу', bn: 'ইয়া ইশু রাবোতু', bnMeaning: 'আমি কাজ খুঁজছি', en: 'I am looking for a job' },
{ ru: 'Можно заплатить картой?', bn: 'মোজনো জাপ্লাতিত কার্তই?', bnMeaning: 'কার্ড দিয়ে কি পরিশোধ করা যাবে?', en: 'Can I pay by card?' },
{ ru: 'Где находится аптека?', bn: 'গ্দে নাখোডিতসা আপতেকা?', bnMeaning: 'ফার্মেসি কোথায়?', en: 'Where is the pharmacy?' },
{ ru: 'Мне нужна сим-карта', bn: 'মনে নুঝনা সিম-কার্তা', bnMeaning: 'আমার একটি সিম কার্ড দরকার', en: 'I need a SIM card' },
{ ru: 'Как пользоваться метро?', bn: 'কাক পল্যজোভাতসা মেত্রো?', bnMeaning: 'মেট্রো কীভাবে ব্যবহার করব?', en: 'How to use the metro?' },
{ ru: 'Я плохо себя чувствую', bn: 'ইয়া প্লোখা সেব্যা চুভствуইউ', bnMeaning: 'আমি অসুস্থ অনুভব করছি', en: 'I feel sick' },
{ ru: 'Где купить билет на поезд?', bn: 'গ্দে কুপিত বিলেত না পোয়েজদ?', bnMeaning: 'ট্রেনের টিকিট কোথায় কিনব?', en: 'Where can I buy a train ticket?' },
{ ru: 'У меня есть страховка', bn: 'উ মেনিয়া ইয়েস্ত স্ত্রাখোভকা', bnMeaning: 'আমার বীমা আছে', en: 'I have insurance' },
{ ru: 'Вы говорите по-английски?', bn: 'ভ্যি গাভারিতে পা-আনগ্লিসকি?', bnMeaning: 'আপনি কি ইংরেজি বলতে পারেন?', en: 'Do you speak English?' },
    { ru: 'Где ближайший банкомат?', bn: 'গ্দে ব্লিজাইশি ব্যাংকমাত?', bnMeaning: 'নিকটতম এটিএম কোথায়?', en: 'Where is the nearest ATM?' },
{ ru: 'Мне нужно открыть банковский счёт', bn: 'মনে নুঝনা আতক্রিত ব্যাংকভস্কি শ্যত', bnMeaning: 'আমার একটি ব্যাংক অ্যাকাউন্ট খুলতে হবে', en: 'I need to open a bank account' },
{ ru: 'У вас есть карта города?', bn: 'উ ভাস ইয়েস্ত কার্তা গোরাদা?', bnMeaning: 'আপনার কাছে শহরের মানচিত্র আছে?', en: 'Do you have a city map?' },
{ ru: 'Я только приехал в Россию', bn: 'ইয়া তল্কা প্রিয়েখাল ফ রসিইউ', bnMeaning: 'আমি সদ্য রাশিয়ায় এসেছি', en: 'I just arrived in Russia' },
{ ru: 'Какой сегодня день?', bn: 'কাকই সিভোদনিয়া দেন?', bnMeaning: 'আজকে কী দিন?', en: 'What day is it today?' },
{ ru: 'Где находится библиотека?', bn: 'গ্দে নাখোডিতসা বিলিয়োতেকা?', bnMeaning: 'লাইব্রেরি কোথায়?', en: 'Where is the library?' },
{ ru: 'Можно взять это на вынос?', bn: 'মোজনো ভজ্যাৎ এটা না ভুইনস?', bnMeaning: 'আমি কি এটা নিয়ে যেতে পারি?', en: 'Can I take this to go?' },
{ ru: 'У меня нет наличных', bn: 'উ মেনিয়া নেইত নালিচনিখ', bnMeaning: 'আমার কাছে নগদ টাকা নেই', en: 'I don’t have cash' },
{ ru: 'Когда начинается занятие?', bn: 'কাগদা নাচিনায়েতসা জানিয়াতিয়ে?', bnMeaning: 'ক্লাস কখন শুরু হবে?', en: 'When does the class start?' },
{ ru: 'Я живу в общежитии', bn: 'ইয়া ঝিভু ভ আপশেজিতিয়ি', bnMeaning: 'আমি হোস্টেলে থাকি', en: 'I live in a dormitory' },
{ ru: 'Как добраться до метро?', bn: 'কাক দাবরাতসা দা মেত্রো?', bnMeaning: 'মেট্রোতে কীভাবে যাওয়া যায়?', en: 'How to get to the metro?' },
{ ru: 'Это очень срочно', bn: 'এটা অচিন স্রোচনো', bnMeaning: 'এটা খুব জরুরি', en: 'This is very urgent' },
{ ru: 'Я потерял паспорт', bn: 'ইয়া পাতেরিয়াল পাস্পোরত', bnMeaning: 'আমি পাসপোর্ট হারিয়েছি', en: 'I lost my passport' },
{ ru: 'Где находится полицейский участок?', bn: 'গ্দে নাখোডিতসা পলিতসেইস্কি উচাস্তক?', bnMeaning: 'পুলিশ স্টেশন কোথায়?', en: 'Where is the police station?' },
{ ru: 'Мне нужна виза', bn: 'মনে নুঝনা ভিজা', bnMeaning: 'আমার ভিসা দরকার', en: 'I need a visa' },
{ ru: 'У меня назначена встреча', bn: 'উ মেনিয়া নাজনাচেনা ফ্সত্রেচা', bnMeaning: 'আমার একটি অ্যাপয়েন্টমেন্ট আছে', en: 'I have an appointment' },
{ ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতে পা আঙ্গলিস্কি?', bnMeaning: 'আপনি কি ইংরেজি বলতে পারেন?', en: 'Do you speak English?' },
{ ru: 'Где можно купить билет?', bn: 'গ্দে মোজনো কুপিত বিলিয়েত?', bnMeaning: 'টিকিট কোথায় কিনতে পারি?', en: 'Where can I buy a ticket?' },
{ ru: 'У меня нет интернета', bn: 'উ মেনিয়া নেইত ইন্টারনেতা', bnMeaning: 'আমার ইন্টারনেট নেই', en: 'I have no internet' },
{ ru: 'Как подключиться к Wi-Fi?', bn: 'কাক পদক্লুচিতসা ক ভাই ফাই?', bnMeaning: 'Wi-Fi-তে কীভাবে সংযুক্ত হব?', en: 'How to connect to Wi-Fi?' },
{ ru: 'Мне нужно продлить регистрацию', bn: 'মনে নুঝনা প্রাদলিত রেগিসত্রাচিউ', bnMeaning: 'আমাকে রেজিস্ট্রেশন বাড়াতে হবে', en: 'I need to extend my registration' },
{ ru: 'Где я могу открыть банковский счёт?', bn: 'গ্দে ইয়া মাগু অকরিত বানকোভস্কি শ্যত?', bnMeaning: 'আমি কোথায় ব্যাংক অ্যাকাউন্ট খুলতে পারি?', en: 'Where can I open a bank account?' },
{ ru: 'Когда следующая пара?', bn: 'কাগদা স্লেদুউশায়া পারা?', bnMeaning: 'পরবর্তী ক্লাস কখন?', en: 'When is the next class?' },
{ ru: 'У меня нет жилья', bn: 'উ মেনিয়া নেইত ঝিল্যা', bnMeaning: 'আমার থাকার জায়গা নেই', en: 'I have no accommodation' },
{ ru: 'Мне нужно арендовать квартиру', bn: 'মনে নুঝনা আরেনদোভাত কভারতিরু', bnMeaning: 'আমাকে একটি ফ্ল্যাট ভাড়া নিতে হবে', en: 'I need to rent an apartment' },
{ ru: 'Где находится общежитие?', bn: 'গ্দে নাখোডিতসা অবশিজিতিয়ে?', bnMeaning: 'হোস্টেল কোথায়?', en: 'Where is the dormitory?' },
{ ru: 'Сколько стоит проездной билет?', bn: 'স্কলকো স্তোইত প্রায়েঝনয় বিলিয়েত?', bnMeaning: 'মাসিক পাসের দাম কত?', en: 'How much is the travel pass?' },
{ ru: 'Где ближайшая аптека?', bn: 'গ্দে ব্লিজাইশায়া আপত্যেকা?', bnMeaning: 'নিকটস্থ ফার্মেসি কোথায়?', en: 'Where is the nearest pharmacy?' },
{ ru: 'Мне нужна сим-карта', bn: 'মনে নুঝনা সিম কার্তা', bnMeaning: 'আমার একটি সিমকার্ড দরকার', en: 'I need a SIM card' },
{ ru: 'Это лекарство от простуды?', bn: 'এটা লেকারস্তভো অত প্রস্তুদি?', bnMeaning: 'এটা কি ঠান্ডার ওষুধ?', en: 'Is this medicine for cold?' },
    { ru: 'У меня нет интернета', bn: 'উ মেনিয়া ন্যেত ইন্টারনেতা', bnMeaning: 'আমার ইন্টারনেট নেই', en: 'I don’t have internet' },
{ ru: 'Как подключиться к Wi-Fi?', bn: 'কাক পাদকল্যুচিতসা ক ভাই-ফাই?', bnMeaning: 'Wi-Fi-তে কীভাবে সংযোগ করবো?', en: 'How to connect to Wi-Fi?' },
{ ru: 'Где можно купить проездной?', bn: 'গ্দে মোজনো কুপিত প্রায়েজনয়?', bnMeaning: 'মাসিক যাত্রা পাস কোথায় কিনতে পারি?', en: 'Where can I buy a travel pass?' },
{ ru: 'Где находится библиотека?', bn: 'গ্দে নাখোডিতসা বিলিব্লিওতেকা?', bnMeaning: 'লাইব্রেরি কোথায়?', en: 'Where is the library?' },
{ ru: 'Сколько длится лекция?', bn: 'স্কলকো দিলিৎসা লেকতসিয়া?', bnMeaning: 'লেকচার কতক্ষণ স্থায়ী হয়?', en: 'How long is the lecture?' },
{ ru: 'Какой у нас кабинет?', bn: 'কাকই উ নাস কাবিনিয়েত?', bnMeaning: 'আমাদের কোন ক্লাসরুম?', en: 'Which classroom is ours?' },
{ ru: 'Где находится консульство?', bn: 'গ্দে নাখোডিতসা কনসুলস্তভা?', bnMeaning: 'কনস্যুলেট কোথায়?', en: 'Where is the consulate?' },
{ ru: 'Как позвонить в Бангладеш?', bn: 'কাক পাজভনিত ভে বাংলাদেশ?', bnMeaning: 'বাংলাদেশে কীভাবে ফোন করবো?', en: 'How to call Bangladesh?' },
{ ru: 'Где можно купить продукты?', bn: 'গ্দে মোজনো কুপিত প্রাদুক্তি?', bnMeaning: 'খাবার কোথায় কিনতে পারি?', en: 'Where can I buy groceries?' },
{ ru: 'Я живу с друзьями', bn: 'ইয়া ঝিভু স দ্রুযিয়ামি', bnMeaning: 'আমি বন্ধুদের সাথে থাকি', en: 'I live with friends' },

    { ru: 'Когда начинается занятие?', bn: 'কাগদা নাচিনায়েতসা জানিয়াতিয়ে?', bnMeaning: 'ক্লাস কখন শুরু হয়?', en: 'When does the class start?' },
{ ru: 'Где можно поесть дешево?', bn: 'গ্দে মোজনো পায়েсть দেশেভা?', bnMeaning: 'সস্তায় কোথায় খাওয়া যায়?', en: 'Where can I eat cheaply?' },
{ ru: 'У меня нет времени', bn: 'উ মেনিয়া ন্যেত ভ্রেমেনি', bnMeaning: 'আমার সময় নেই', en: 'I don’t have time' },
{ ru: 'Я изучаю русский язык', bn: 'ইয়া ইজুচায়ু রুস্কি ইয়াজিক', bnMeaning: 'আমি রাশিয়ান ভাষা শিখছি', en: 'I am learning Russian language' },
{ ru: 'Помогите, пожалуйста', bn: 'পামাগিতে, পাঝালুস্তা', bnMeaning: 'দয়া করে সাহায্য করুন', en: 'Please help me' },
{ ru: 'Мне нужно зарядить телефон', bn: 'মনে নুঝনা জরিয়াদিত তেলিফোন', bnMeaning: 'আমার ফোন চার্জ করতে হবে', en: 'I need to charge my phone' },
{ ru: 'Это моя первая зима здесь', bn: 'এতা ময়া পিয়েরভায়া জিমা জদেস', bnMeaning: 'এটাই আমার এখানে প্রথম শীত', en: 'This is my first winter here' },
{ ru: 'Можно оплатить картой?', bn: 'মোজনো আপলাতিত কারতই?', bnMeaning: 'কার্ড দিয়ে পরিশোধ করা যাবে?', en: 'Can I pay by card?' },
{ ru: 'Где можно снять квартиру?', bn: 'গ্দে মোজনো স্ন্যাত কাভারতিরু?', bnMeaning: 'ফ্ল্যাট ভাড়া কোথায় পাওয়া যাবে?', en: 'Where can I rent an apartment?' },
{ ru: 'Мне нужно купить учебники', bn: 'মনে নুঝনা কুপিত উচেবনিঙ্কি', bnMeaning: 'আমাকে বই কিনতে হবে', en: 'I need to buy textbooks' },

  { ru: 'Привет', bn: 'প্রিভিয়েত', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Спасибо', bn: 'স্পাসিবো', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Как дела?', bn: 'কাক দেলা?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' },
  { ru: 'Здравствуйте', bn: 'জদরাভস্তভুইত্যে', bnMeaning: 'শুভ দিন', en: 'Hello (formal)' },
  { ru: 'Пожалуйста', bn: 'পাঝালুস্তা', bnMeaning: 'দয়া করে / স্বাগতম', en: "Please / You're welcome" },
  { ru: 'Извините', bn: 'ইজভিনিতিয়ে', bnMeaning: 'মাফ করবেন', en: 'Excuse me / Sorry' },
  { ru: 'Где находится больница?', bn: 'গ্দে নাখোডিতসা বলনিতসা?', bnMeaning: 'হাসপাতাল কোথায়?', en: 'Where is the hospital?' },
  { ru: 'Сколько это стоит?', bn: 'স্কলকো এইতা স্তোইত?', bnMeaning: 'এটার দাম কত?', en: 'How much does it cost?' },
  { ru: 'Я не понимаю', bn: 'ইয়া নি পনিমায়ু', bnMeaning: 'আমি বুঝতে পারছি না', en: "I don't understand" },
  { ru: 'Говорите медленнее, пожалуйста', bn: 'গাভারিতে মেদলেন্নিয়ে, পাঝালুস্তা', bnMeaning: 'দয়া করে ধীরে বলুন', en: 'Please speak slowly' },
  { ru: 'Я хочу воды', bn: 'ইয়া খাচু ভাদি', bnMeaning: 'আমার পানি দরকার', en: 'I want water' },
  { ru: 'Который час?', bn: 'কাতোরি চাস?', bnMeaning: 'কয়টা বাজে?', en: 'What time is it?' },
  { ru: 'Мне нужна помощь', bn: 'মনে নুঝনা পোমোশ', bnMeaning: 'আমার সাহায্য দরকার', en: 'I need help' },
  { ru: 'Где ближайший магазин?', bn: 'গ্দে ব্লিজাইশি মাগাজিন?', bnMeaning: 'নিকটতম দোকান কোথায়?', en: 'Where is the nearest shop?' },
  { ru: 'Я студент', bn: 'ইয়া স্টুডেন্ট', bnMeaning: 'আমি একজন ছাত্র', en: 'I am a student' },
  { ru: 'Можно меню?', bn: 'মোজনো মেন্যু?', bnMeaning: 'মেনু পেতে পারি?', en: 'Can I have the menu?' },
  { ru: 'Где автобусная остановка?', bn: 'গ্দে আফতোবুসনায়া অস্তানোভকা?', bnMeaning: 'বাস স্টপ কোথায়?', en: 'Where is the bus stop?' },
  { ru: 'Мне нужно такси', bn: 'মনে নুঝনা তাকসি', bnMeaning: 'আমার ট্যাক্সি দরকার', en: 'I need a taxi' },
  { ru: 'Как пройти к университету?', bn: 'কাক প্রাইটি ক ইউনিভার্সিতেতু?', bnMeaning: 'বিশ্ববিদ্যালয়ে যাওয়ার রাস্তা কী?', en: 'How to get to the university?' },
  { ru: 'У меня аллергия', bn: 'উ মেনিয়া অ্যালারগিয়া', bnMeaning: 'আমার অ্যালার্জি আছে', en: 'I have an allergy' },
  { ru: 'Я заблудился', bn: 'ইয়া জাবলুদিলসা', bnMeaning: 'আমি পথ হারিয়েছি', en: 'I am lost' },
  
  { ru: 'Где туалет?', bn: 'গ্দে তুয়ালেত?', bnMeaning: 'শৌচাগার কোথায়?', en: 'Where is the toilet?' },
  { ru: 'Я потерял паспорт', bn: 'ইয়া পাতেরল পাসপোরত', bnMeaning: 'আমি পাসপোর্ট হারিয়েছি', en: 'I lost my passport' },
  { ru: 'Помогите, пожалуйста', bn: 'পোমোগিতে, পাঝালুস্তা', bnMeaning: 'দয়া করে সাহায্য করুন', en: 'Please help me' },
  { ru: 'Я не говорю по-русски', bn: 'ইয়া নি গাভারু পো-রুস্কি', bnMeaning: 'আমি রাশিয়ান ভাষা বলতে পারি না', en: 'I don’t speak Russian' },
  { ru: 'Где ближайшая аптека?', bn: 'গ্দে ব্লিজাইশা আপ্তেকা?', bnMeaning: 'নিকটস্থ ওষুধের দোকান কোথায়?', en: 'Where is the nearest pharmacy?' },
  { ru: 'Я живу в общежитии', bn: 'ইয়া জিভু ভ অব্শেচিতি', bnMeaning: 'আমি হোস্টেলে থাকি', en: 'I live in a dormitory' },
  { ru: 'Сколько стоит билет?', bn: 'স্কলকো স্তোইত বিলেত?', bnMeaning: 'টিকিটের দাম কত?', en: 'How much is the ticket?' },
  { ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতে পো-আঙ্গলিস্কি?', bnMeaning: 'আপনি ইংরেজি বলতে পারেন?', en: 'Do you speak English?' },
  { ru: 'Можно счет, пожалуйста?', bn: 'মোজনো শচেত, পাঝালুস্তা?', bnMeaning: 'বিল দিতে পারবেন?', en: 'Can I have the bill, please?' },
  { ru: 'Я изучаю русский язык', bn: 'ইয়া ইজুচায়ু রুস্কি ইয়াজিক', bnMeaning: 'আমি রাশিয়ান ভাষা শিখছি', en: 'I am learning Russian' },
  { ru: 'Где банк?', bn: 'গ্দে ব্যাংক?', bnMeaning: 'ব্যাংক কোথায়?', en: 'Where is the bank?' },
  { ru: 'Можно фотографировать?', bn: 'মোজনো ফতোগ্রাফিরোভাত?', bnMeaning: 'আমি ছবি তুলতে পারি?', en: 'Can I take pictures?' },
  { ru: 'У меня бронхит', bn: 'উ মেনিয়া ব্রোন্হিত', bnMeaning: 'আমার ব্রংকাইটিস হয়েছে', en: 'I have bronchitis' },
  { ru: 'Как пройти в парк?', bn: 'কাক প্রাইতি ভ পার্ক?', bnMeaning: 'পার্কে কিভাবে যাব?', en: 'How to get to the park?' },
  { ru: 'Я работаю студентом', bn: 'ইয়া রবোতায়ু স্টুডেন্তম', bnMeaning: 'আমি একজন ছাত্র হিসেবে কাজ করি', en: 'I work as a student' },
  { ru: 'Мне нужна помощь врача', bn: 'মনে নুঝনা পোমোশ ভ্রাচা', bnMeaning: 'আমার ডাক্তারের সাহায্য দরকার', en: 'I need a doctor’s help' },
  { ru: 'Где метро?', bn: 'গ্দে মেত্রো?', bnMeaning: 'মেট্রো কোথায়?', en: 'Where is the metro?' },
  { ru: 'Это дорого', bn: 'এইতা দোরোগো', bnMeaning: 'এটা দামি', en: 'It is expensive' },
  { ru: 'Я хочу поесть', bn: 'ইয়া খাচু পোয়েস্ট', bnMeaning: 'আমি খেতে চাই', en: 'I want to eat' },
  { ru: 'Говорите медленнее', bn: 'গাভারিতে মেদলেন্নিয়ে', bnMeaning: 'ধীরে বলুন', en: 'Speak slowly' },
  { ru: 'Когда отправляется поезд?', bn: 'কগদা অস্তাভলাযেতসা পোইযেদ?', bnMeaning: 'ট্রেন কখন ছাড়ে?', en: 'When does the train leave?' },
  { ru: 'Мне нужно купить билет', bn: 'মনে নুঝনা কুপিত বিলেত', bnMeaning: 'আমাকে টিকিট কিনতে হবে', en: 'I need to buy a ticket' },
  { ru: 'Где я могу найти такси?', bn: 'গ্দে ইয়া মগু নায়তি তাক্সি?', bnMeaning: 'আমি কোথায় ট্যাক্সি পাব?', en: 'Where can I find a taxi?' },
  { ru: 'Вы можете помочь мне?', bn: 'ভি মোঝেতে পোমচ ম্নে?', bnMeaning: 'আপনি আমাকে সাহায্য করতে পারেন?', en: 'Can you help me?' },
  { ru: 'Какая погода сегодня?', bn: 'কাকাইা পোগোদা সিয়োদ্না?', bnMeaning: 'আজকের আবহাওয়া কেমন?', en: 'What is the weather like today?' },
  { ru: 'Мне холодно', bn: 'মনে খলোদনা', bnMeaning: 'আমার ঠান্ডা লাগছে', en: 'I am cold' },
  { ru: 'Я устал', bn: 'ইয়া উস্তাল', bnMeaning: 'আমি ক্লান্ত', en: 'I am tired' },
  { ru: 'Где находится банк?', bn: 'গ্দে নাখোদিতসা ব্যাংক?', bnMeaning: 'ব্যাংক কোথায় অবস্থিত?', en: 'Where is the bank located?' },
  { ru: 'Можно заплатить картой?', bn: 'মোজনো জাপলাতিত কার্তয়?', bnMeaning: 'কার্ড দিয়ে পেমেন্ট করা যাবে?', en: 'Can I pay by card?' },
  { ru: 'Я хочу пить', bn: 'ইয়া খাচু পিত', bnMeaning: 'আমি পানি খেতে চাই', en: 'I want to drink' },
  { ru: 'Вы говорите по-русски?', bn: 'ভি গাভারিতে পো-রুস্কি?', bnMeaning: 'আপনি রাশিয়ান ভাষায় কথা বলেন?', en: 'Do you speak Russian?' },
  { ru: 'Где ближайший магазин?', bn: 'গ্দে ব্লিজাইশি মাগাজিন?', bnMeaning: 'নিকটতম দোকান কোথায়?', en: 'Where is the nearest store?' },
  { ru: 'Сколько это стоит?', bn: 'স্কলকো এইতা স্তোইত?', bnMeaning: 'এটার দাম কত?', en: 'How much does this cost?' },
  { ru: 'Можно ли здесь курить?', bn: 'মোজনো লি যেদ্স কুরিত?', bnMeaning: 'এখানে ধূমপান করা যাবে?', en: 'Is smoking allowed here?' },
  { ru: 'Где я могу поесть?', bn: 'গ্দে ইয়া মগু পোয়েস্ট?', bnMeaning: 'আমি কোথায় খেতে পারি?', en: 'Where can I eat?' },
  { ru: 'Я заблудился', bn: 'ইয়া জাবলুদিলসা', bnMeaning: 'আমি পথ হারিয়েছি', en: 'I am lost' },
  { ru: 'Пожалуйста, говорите медленнее', bn: 'পাঝালুস্তা, গাভারিতে মেদলেন্নিয়ে', bnMeaning: 'দয়া করে ধীরে বলুন', en: 'Please speak more slowly' },
  { ru: 'Я не понимаю', bn: 'ইয়া নি পোনিমায়ু', bnMeaning: 'আমি বুঝতে পারছি না', en: 'I don’t understand' },
  { ru: 'Можно ли здесь сделать фотографию?', bn: 'মোজনো লি যেদ্স সদেলাত ফতোগ্রাফিউ?', bnMeaning: 'এখানে ছবি তোলা যাবে?', en: 'Can I take a photo here?' },
  { ru: 'Я учусь в университете', bn: 'ইয়া উচুস ভ উনিভেরসিতেতে', bnMeaning: 'আমি বিশ্ববিদ্যালয়ে পড়াশোনা করি', en: 'I study at the university' },
  
  { ru: 'Как пройти в библиотеку?', bn: 'কাক প্রইতি ভ বিলিয়োটেকু?', bnMeaning: 'লাইব্রেরি যেতে কেমন যাবে?', en: 'How do I get to the library?' },
  { ru: 'Мне нужна помощь с домашним заданием', bn: 'মনে নুঝনা পোমোচ স দমাশনিম জাদানিয়েম', bnMeaning: 'আমার হোমওয়ার্কে সাহায্য দরকার', en: 'I need help with my homework' },
  { ru: 'Во сколько начинается урок?', bn: 'ভো স্কলকো নাচিনায়েতসা উরক?', bnMeaning: 'কতটায় ক্লাস শুরু হয়?', en: 'What time does the lesson start?' },
  { ru: 'Можно ли пользоваться интернетом?', bn: 'মোজনো লি পোলোঝিতসা ইন্টারনেতম?', bnMeaning: 'ইন্টারনেট ব্যবহার করা যাবে?', en: 'Can I use the internet?' },
  { ru: 'Я хочу заказать еду', bn: 'ইয়া খাচু জাকাজাত এদু', bnMeaning: 'আমি খাবার অর্ডার করতে চাই', en: 'I want to order food' },
  { ru: 'Где ближайшая аптека?', bn: 'গ্দে ব্লিজাইশা আপতেকা?', bnMeaning: 'নিকটতম ফার্মেসি কোথায়?', en: 'Where is the nearest pharmacy?' },
  { ru: 'Мне нужен врач', bn: 'মনে নুঝেন ভ্রাচ', bnMeaning: 'আমাকে একজন ডাক্তার দরকার', en: 'I need a doctor' },
  { ru: 'Я ищу жилье', bn: 'ইয়া ইশচু জিলয়ে', bnMeaning: 'আমি বাসস্থান খুঁজছি', en: 'I am looking for accommodation' },
  { ru: 'Какая остановка следующая?', bn: 'কাকাইা অস্তানোভকা স্লেদুজায়া?', bnMeaning: 'পরবর্তী স্টপ কোনটা?', en: 'What is the next stop?' },
  { ru: 'Можно ли оплатить наличными?', bn: 'মোজনো লি অপলাতিত নালিচনিমি?', bnMeaning: 'ক্যাশ দিয়ে পেমেন্ট করা যাবে?', en: 'Can I pay in cash?' },
  { ru: 'Как добраться до аэропорта?', bn: 'কাক দুরাতসা দো অ্যারোপর্তা?', bnMeaning: 'এয়ারপোর্টে কীভাবে যাব?', en: 'How do I get to the airport?' },
  { ru: 'Вы говорите по-английски?', bn: 'ভি গাভারিতে পো-আঙ্গলিস্কি?', bnMeaning: 'আপনি ইংরেজিতে কথা বলেন?', en: 'Do you speak English?' },
  { ru: 'Сколько времени занимает дорога?', bn: 'স্কলকো ভ্রমেনি জানিমায়েত দোরোগা?', bnMeaning: 'রাস্তায় কতক্ষণ সময় লাগে?', en: 'How long does the trip take?' },
  { ru: 'Где находится посольство?', bn: 'গ্দে নাখোদিতসা পোসোলস্তভ?', bnMeaning: 'দূতাবাস কোথায়?', en: 'Where is the embassy?' },
  { ru: 'Можно ли здесь оставить вещи?', bn: 'মোজনো লি যেদ্স ওস্তাবিত ভেশি?', bnMeaning: 'এখানে জিনিস রাখতে পারি?', en: 'Can I leave my things here?' },
  { ru: 'Я забыл паспорт', bn: 'ইয়া জাবিল পাসপর্ত', bnMeaning: 'আমি পাসপোর্ট ভুলে গেছি', en: 'I forgot my passport' },
  { ru: 'Где я могу снять деньги?', bn: 'গ্দে ইয়া মগু স্নিয়াত দেনজি?', bnMeaning: 'আমি কোথায় টাকা তুলতে পারি?', en: 'Where can I withdraw money?' },
  { ru: 'Можно ли сделать скидку?', bn: 'মোজনো লি সদেলাত স্কিদকু?', bnMeaning: 'ছাড় পাওয়া যাবে?', en: 'Can I get a discount?' },
  { ru: 'У вас есть меню на английском?', bn: 'উ ভাস এস্ত মেনু না আঙ্গলিসকম?', bnMeaning: 'আপনার কাছে ইংরেজি মেনু আছে?', en: 'Do you have a menu in English?' },
  { ru: 'Где находится туалет?', bn: 'গ্দে নাখোদিতসা তুয়ালেত?', bnMeaning: 'টয়লেট কোথায়?', en: 'Where is the restroom?' },
{ ru: 'Я хочу открыть банковский счет', bn: 'ইয়া খাচু আতকৃৎ ব্যাংকভস্কি শচ্যত', bnMeaning: 'আমি একটি ব্যাংক অ্যাকাউন্ট খুলতে চাই', en: 'I want to open a bank account' },
{ ru: 'Какой у вас номер телефона?', bn: 'কাকই উ ভাস নোমের তেলেফোনা?', bnMeaning: 'আপনার ফোন নাম্বার কী?', en: 'What is your phone number?' },
{ ru: 'Я не понимаю', bn: 'ইয়া নে পনিমায়ু', bnMeaning: 'আমি বুঝতে পারছি না', en: 'I don’t understand' },
{ ru: 'Пожалуйста, повторите', bn: 'পাঝালুস্তা, পাফতারিতে', bnMeaning: 'দয়া করে আবার বলুন', en: 'Please repeat' },
{ ru: 'Говорите медленно, пожалуйста', bn: 'গাভারিতে মেদলেন্না, পাঝালুস্তা', bnMeaning: 'দয়া করে ধীরে বলুন', en: 'Please speak slowly' },
{ ru: 'Где ближайшая автобусная остановка?', bn: 'গ্দে ব্লিজাইশায়া আফতোবুসনায়া অস্তানোভকা?', bnMeaning: 'নিকটবর্তী বাস স্টপ কোথায়?', en: 'Where is the nearest bus stop?' },
{ ru: 'Сколько стоит проезд?', bn: 'স্কলকো স্তইৎ প্রোয়েয্দ?', bnMeaning: 'যাতায়াতে খরচ কত?', en: 'How much is the fare?' },
{ ru: 'Я студент', bn: 'ইয়া স্টুডেন্ত', bnMeaning: 'আমি একজন ছাত্র', en: 'I am a student' },
{ ru: 'Где я могу купить проездной билет?', bn: 'গ্দে ইয়া মাগু কুপিত প্রোয়েজনই বিলিয়েত?', bnMeaning: 'আমি কোথায় ট্রাভেল টিকেট কিনতে পারি?', en: 'Where can I buy a travel pass?' },
{ ru: 'Я опоздал на урок', bn: 'ইয়া আপাজদাল না উরক', bnMeaning: 'আমি ক্লাসে দেরি করেছি', en: 'I am late for class' },
{ ru: 'У меня есть домашнее задание', bn: 'উ মেন্যা এস্ত দমাশনিয়ে জাদানিয়ে', bnMeaning: 'আমার হোমওয়ার্ক আছে', en: 'I have homework' },
{ ru: 'Можно ли задать вопрос?', bn: 'মোজনো লি জাদাত ভাপরোস?', bnMeaning: 'একটা প্রশ্ন করতে পারি?', en: 'Can I ask a question?' },
{ ru: 'Я ищу работу', bn: 'ইয়া ইশচু রাবোতু', bnMeaning: 'আমি চাকরি খুঁজছি', en: 'I am looking for a job' },
{ ru: 'Где находится университет?', bn: 'গ্দে নাখোদিতসা উনিভেরসিতেত?', bnMeaning: 'বিশ্ববিদ্যালয় কোথায়?', en: 'Where is the university?' },
{ ru: 'Я учусь на первом курсе', bn: 'ইয়া উচুস না পিয়েরভম কুরসে', bnMeaning: 'আমি প্রথম বর্ষে পড়ি', en: 'I am in the first year' },
{ ru: 'Как зовут вашего преподавателя?', bn: 'কাক জাভুত ভাশেভা প্রেপодавাতেল্যা?', bnMeaning: 'আপনার শিক্ষক/শিক্ষিকার নাম কী?', en: 'What is your teacher’s name?' },
{ ru: 'Можно задать вопрос по грамматике?', bn: 'মোজনো জাদাত ভাপরোস পা গ্রামাতিকে?', bnMeaning: 'ব্যাকরণ নিয়ে প্রশ্ন করা যাবে?', en: 'Can I ask a grammar question?' },
{ ru: 'Я живу в общежитии', bn: 'ইয়া ঝিভু ভ আবশেজিতিই', bnMeaning: 'আমি হোস্টেলে থাকি', en: 'I live in a dormitory' },
{ ru: 'Когда будет экзамен?', bn: 'কগদা বুদেত একজামেন?', bnMeaning: 'পরীক্ষা কবে হবে?', en: 'When is the exam?' },
{ ru: 'Сколько длится курс?', bn: 'স্কলকো দ্লিতসা কুর্স?', bnMeaning: 'কোর্সটি কতদিনের?', en: 'How long is the course?' },
{ ru: 'Где находится библиотека?', bn: 'গ্দে নাখোদিতসা বিলিওতেকা?', bnMeaning: 'লাইব্রেরি কোথায়?', en: 'Where is the library?' },
{ ru: 'Я хочу взять книгу', bn: 'ইয়া খাচু ভজ্যাত কিনিগু', bnMeaning: 'আমি একটি বই নিতে চাই', en: 'I want to borrow a book' },
{ ru: 'Сколько стоит аренда?', bn: 'স্কলকো স্তইৎ অ্যারেনদা?', bnMeaning: 'ভাড়া কত?', en: 'How much is the rent?' },
{ ru: 'Я ищу квартиру', bn: 'ইয়া ইশচু কভারতিরু', bnMeaning: 'আমি একটি অ্যাপার্টমেন্ট খুঁজছি', en: 'I am looking for an apartment' },
{ ru: 'Можно посмотреть комнату?', bn: 'মোজনো পাসমত্রেত কমনাতু?', bnMeaning: 'আমি কি রুমটা দেখতে পারি?', en: 'Can I see the room?' },
{ ru: 'Когда начинается урок?', bn: 'কগদা নাচিনায়েতসা উরক?', bnMeaning: 'ক্লাস কখন শুরু হয়?', en: 'When does the class start?' },
{ ru: 'Во сколько открывается офис?', bn: 'ভো স্কলকো আৎক্রিভাইতসা অফিস?', bnMeaning: 'অফিস কখন খুলে?', en: 'What time does the office open?' },
{ ru: 'У меня нет времени', bn: 'উ মেন্যা নিএত ভরেমেনি', bnMeaning: 'আমার সময় নেই', en: 'I don’t have time' },
{ ru: 'Я устал', bn: 'ইয়া উস্তাল', bnMeaning: 'আমি ক্লান্ত', en: 'I am tired' },
{ ru: 'Мне нужно отдохнуть', bn: 'মনে নুজনা আতдохনুত', bnMeaning: 'আমার বিশ্রাম দরকার', en: 'I need to rest' },
{ ru: 'У меня есть документы', bn: 'উ মেন্যা এস্ত দাকুমেনতি', bnMeaning: 'আমার কাছে ডকুমেন্ট আছে', en: 'I have documents' },
{ ru: 'Пожалуйста, покажите паспорт', bn: 'পাঝালুস্তা, পকাঝিতে পাস্পার্ত', bnMeaning: 'অনুগ্রহ করে পাসপোর্ট দেখান', en: 'Please show your passport' },
{ ru: 'Мне нужна помощь', bn: 'মনে নুঝনা পামশ', bnMeaning: 'আমার সাহায্য দরকার', en: 'I need help' },
{ ru: 'Позовите, пожалуйста, врача', bn: 'পাজাভিতে, পাঝালুস্তা, ভ্রাচা', bnMeaning: 'একজন ডাক্তার ডাকুন', en: 'Please call a doctor' },
{ ru: 'У меня аллергия', bn: 'উ মেন্যা অ্যালেরগিয়া', bnMeaning: 'আমার অ্যালার্জি আছে', en: 'I have an allergy' },
{ ru: 'Где находится аптека?', bn: 'গ্দে নাখোদিতসা আপতেকা?', bnMeaning: 'ফার্মেসি কোথায়?', en: 'Where is the pharmacy?' },
{ ru: 'Я потерял паспорт', bn: 'ইয়া পাতেরিয়াল পাস্পার্ত', bnMeaning: 'আমি পাসপোর্ট হারিয়েছি', en: 'I lost my passport' },
{ ru: 'Что мне делать?', bn: 'শতো ম্নে দিলাত?', bnMeaning: 'আমার কী করা উচিত?', en: 'What should I do?' },
{ ru: 'У вас есть свободные места?', bn: 'উ ভাস এস্ত সভাবদনিয়ে মেস্তা?', bnMeaning: 'আপনারা কি ফাঁকা সিট পান?', en: 'Do you have available seats?' },
{ ru: 'Где можно поесть?', bn: 'গ্দে মোজনো পায়েস্ট?', bnMeaning: 'খাওয়ার জায়গা কোথায়?', en: 'Where can I eat?' },
// রাশিয়া শেষ  আরো এড করলে এই লেখার উপরে এড করুন।
  ],
  german: [
  { ru: 'Hallo', bn: 'হালো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Guten Morgen', bn: 'গুটেন মর্গেন', bnMeaning: 'শুভ সকাল', en: 'Good morning' },
  { ru: 'Guten Abend', bn: 'গুটেন আবেন্ড', bnMeaning: 'শুভ সন্ধ্যা', en: 'Good evening' },
  { ru: 'Gute Nacht', bn: 'গুটে নাখট', bnMeaning: 'শুভ রাত্রি', en: 'Good night' },
  { ru: 'Wie heißen Sie?', bn: 'ভি হাইসেন জি?', bnMeaning: 'আপনার নাম কী?', en: 'What is your name?' },
  { ru: 'Ich heiße...', bn: 'ইশ হাইসে...', bnMeaning: 'আমার নাম ...', en: 'My name is...' },
  { ru: 'Wie geht es Ihnen?', bn: 'ভি গেট এস ইইনেন?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' },
  { ru: 'Mir geht es gut', bn: 'মিয়ার গেট এস গুট', bnMeaning: 'আমি ভালো আছি', en: 'I am fine' },
  { ru: 'Danke', bn: 'ডাঙ্কে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Bitte', bn: 'বিটে', bnMeaning: 'অনুগ্রহ করে / স্বাগতম', en: 'Please / You\'re welcome' },
  { ru: 'Entschuldigung', bn: 'এন্টশুলডিগুং', bnMeaning: 'মাফ করবেন', en: 'Excuse me / Sorry' },
  { ru: 'Ich verstehe nicht', bn: 'ইশ ফারস্টেহে নিশ্ট', bnMeaning: 'আমি বুঝতে পারছি না', en: 'I don’t understand' },
  { ru: 'Sprechen Sie Englisch?', bn: 'শ্প্রেখেন জি ইংলিশ?', bnMeaning: 'আপনি কি ইংরেজি বলেন?', en: 'Do you speak English?' },
  { ru: 'Wo ist die Toilette?', bn: 'ভো ইস্ট দি টয়লেট্টে?', bnMeaning: 'টয়লেট কোথায়?', en: 'Where is the toilet?' },
  { ru: 'Wie viel kostet das?', bn: 'ভি ফিল কস্টেট দাস?', bnMeaning: 'এটার দাম কত?', en: 'How much does it cost?' },
  { ru: 'Ich brauche Hilfe', bn: 'ইশ ব্রাউখে হিলফে', bnMeaning: 'আমার সাহায্য দরকার', en: 'I need help' },
  { ru: 'Wo ist das Krankenhaus?', bn: 'ভো ইস্ট দাস ক্রাঙ্কেনহাউস?', bnMeaning: 'হাসপাতাল কোথায়?', en: 'Where is the hospital?' },
  { ru: 'Ich bin Student', bn: 'ইশ বিন স্টুডেন্ট', bnMeaning: 'আমি একজন ছাত্র', en: 'I am a student' },
  { ru: 'Ich habe Hunger', bn: 'ইশ হাবে হুংগার', bnMeaning: 'আমার খিদে পেয়েছে', en: 'I am hungry' },
  { ru: 'Ich habe Durst', bn: 'ইশ হাবে ডুর্স্ট', bnMeaning: 'আমার পিপাসা পেয়েছে', en: 'I am thirsty' },
  { ru: 'Hallo', bn: 'হালো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Danke', bn: 'ডাঙ্কে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: "Wie geht's?", bn: 'ভি গেটস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' },
// জার্মানি ভাষা এখানে এড করুন।
  
  
  ],
  italian: [
    { ru: 'Ciao', bn: 'চাও', bnMeaning: 'হ্যালো', en: 'Hello' },
    { ru: 'Grazie', bn: 'গ্রাতসিয়ে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: 'Come stai?', bn: 'কোমে স্তাই?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  french: [
    { ru: 'Bonjour', bn: 'বঁজুর', bnMeaning: 'শুভ সকাল', en: 'Good morning' },
    { ru: 'Merci', bn: 'মেরসি', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: 'Comment ça va?', bn: 'কোমঁ সা ভা?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  spanish: [
    { ru: 'Hola', bn: 'ওলা', bnMeaning: 'হ্যালো', en: 'Hello' },
    { ru: 'Gracias', bn: 'গ্রাসিয়াস', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: '¿Cómo estás?', bn: 'কোমো এসতাস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  portuguese: [
    { ru: 'Olá', bn: 'ওলা', bnMeaning: 'হ্যালো', en: 'Hello' },
    { ru: 'Obrigado', bn: 'ওব্রিগাদো', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: 'Como vai?', bn: 'কোমু ভাই?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  dutch: [
    { ru: 'Hallo', bn: 'হালো', bnMeaning: 'হ্যালো', en: 'Hello' },
    { ru: 'Dank je', bn: 'ডাংক ইয়ে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: 'Hoe gaat het?', bn: 'হু হাত হেট?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  swedish: [
    { ru: 'Hej', bn: 'হেই', bnMeaning: 'হ্যালো', en: 'Hello' },
    { ru: 'Tack', bn: 'তাক', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
    { ru: 'Hur mår du?', bn: 'হুর মোর দু?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
  ],
  norwegian: [
  { ru: 'Hei', bn: 'হেই', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Takk', bn: 'তাক', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Hvordan har du det?', bn: 'হুভোরদান হার দু দে?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
finnish: [
  { ru: 'Hei', bn: 'হেই', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Kiitos', bn: 'কিতোস', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Mitä kuuluu?', bn: 'মিতা কুলু?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
danish: [
  { ru: 'Hej', bn: 'হাই', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Tak', bn: 'তাক', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Hvordan går det?', bn: 'হুভোরদান গর দে?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
polish: [
  { ru: 'Cześć', bn: 'চেশচ', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Dziękuję', bn: 'জিঙ্কুয়ে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Jak się masz?', bn: 'ইয়াক শিয়ে মাশ?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
czech: [
  { ru: 'Ahoj', bn: 'আহয়', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Děkuji', bn: 'দ্যেকুই', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Jak se máš?', bn: 'ইয়াক সে মাস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
hungarian: [
  { ru: 'Helló', bn: 'হেল্লো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Köszönöm', bn: 'কোসোনোম', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Hogy vagy?', bn: 'হগ্য ভগ্য?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
slovak: [
  { ru: 'Ahoj', bn: 'আহয়', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Ďakujem', bn: 'দ্যাকুয়েম', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Ako sa máš?', bn: 'আকো সা মাস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
slovenian: [
  { ru: 'Živjo', bn: 'জিভ্যো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Hvala', bn: 'হভালা', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kako si?', bn: 'কাকো সি?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
croatian: [
  { ru: 'Bok', bn: 'বক', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Hvala', bn: 'হভালা', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kako si?', bn: 'কাকো সি?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
estonian: [
  { ru: 'Tere', bn: 'তেরে', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Aitäh', bn: 'আইতাহ', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kuidas läheb?', bn: 'কুইদাস লাহেব?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
latvian: [
  { ru: 'Sveiki', bn: 'স্ভেইকি', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Paldies', bn: 'পালদিয়েস', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kā jums klājas?', bn: 'কা ইউমস ক্লায়াস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
lithuanian: [
  { ru: 'Labas', bn: 'লাবাস', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Ačiū', bn: 'আচু', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kaip sekasi?', bn: 'কাইপ সেকাসি?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
swiss: [
  { ru: 'Grüezi', bn: 'গ্র্যুয়েতসি', bnMeaning: 'হ্যালো (সুইস জার্মান)', en: 'Hello' },
  { ru: 'Danke', bn: 'ডাঙ্কে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Wie gahts?', bn: 'ভি গ্যাটস?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
maltesian: [
  { ru: 'Bongu', bn: 'বোনগু', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Grazzi', bn: 'গ্রাজজি', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Kif inti?', bn: 'কিফ ইনতি?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
  austrian: [
  { ru: 'Servus', bn: 'সার্ভুস', bnMeaning: 'হ্যালো / বিদায় (অস্ট্রিয়ান স্টাইল)', en: 'Hello / Bye' },
  { ru: 'Danke scheen', bn: 'ডাঙ্কে শেন', bnMeaning: 'ধন্যবাদ (শোভনভাবে)', en: 'Thank you very much' },
  { ru: 'Wie geht’s da?', bn: 'ভি গেটস দা?', bnMeaning: 'আপনি কেমন আছেন? (স্থানীয়)', en: 'How are you?' },
],
icelandic: [
  { ru: 'Halló', bn: 'হাল্লো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Takk', bn: 'তাক', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Hvernig hefur þú það?', bn: 'কভের্নিগ হেভুর থু থাথ?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
liechtenstein: [
  { ru: 'Hallo', bn: 'হালো', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Danke', bn: 'ডাঙ্কে', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Wie geht es Ihnen?', bn: 'ভি গেট এস ইইনেন?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],
luxembourgish: [
  { ru: 'Moien', bn: 'মইয়েন', bnMeaning: 'হ্যালো', en: 'Hello' },
  { ru: 'Merci', bn: 'মেরসি', bnMeaning: 'ধন্যবাদ', en: 'Thank you' },
  { ru: 'Wéi geet et Iech?', bn: 'ভেই গেট এট ইইচ?', bnMeaning: 'আপনি কেমন আছেন?', en: 'How are you?' }
],

};


function renderVocabulary(lang) {
  const data = vocabulary[lang] || [];
  conversationArea.innerHTML = '';

  data.forEach(item => {
    const div = document.createElement('div');
    div.classList.add('conversation-item');
    div.innerHTML = `
      <p><strong>🇷🇺 ${item.ru}</strong></p>
      <p>🔊 উচ্চারণ: ${item.bn}</p>
      <p>📝 বাংলা অর্থ: ${item.bnMeaning}</p>
      <p>🔤 English: ${item.en}</p>
    `;
    conversationArea.appendChild(div);
  });
}

// Load saved language
const savedLang = localStorage.getItem('selectedLanguage');
if (savedLang && vocabulary[savedLang]) {
  languageSelect.value = savedLang;
  renderVocabulary(savedLang);
} else {
  const defaultLang = languageSelect.value;
  localStorage.setItem('selectedLanguage', defaultLang);
  renderVocabulary(defaultLang);
}

// Save on change
languageSelect.addEventListener('change', () => {
  const selected = languageSelect.value;
  localStorage.setItem('selectedLanguage', selected);
  renderVocabulary(selected);
});

// Dark mode memory
const isDark = localStorage.getItem('darkMode') === 'true';
if (isDark) {
  document.body.classList.add('dark-mode');
  modeToggle.textContent = '☀️';
}

modeToggle.addEventListener('click', () => {
  document.body.classList.toggle('dark-mode');
  const isDarkNow = document.body.classList.contains('dark-mode');
  localStorage.setItem('darkMode', isDarkNow);
  modeToggle.textContent = isDarkNow ? '☀️' : '🌙';
});
